// This is copied from bCorporations.json.
export const bCorporations = [
  "company_name",
  "Sustain Natural",
  "Technologies Ecofixe",
  "ARROCERA LA ESMERALDA SAS",
  "Silkwave Industries Co. Ltd.",
  "Hemmings House",
  "DOMI",
  "Borden Communications + Design Inc.",
  "Bark Media",
  "re:focus partners",
  "Teak Media + Communication",
  "Nahua LLC",
  "Guayaki Sustainable Rainforest Products",
  "Gong Communications",
  "Bolsas Reutilizables",
  "W.S. Badger Co, Inc.",
  "Sir Kensington's",
  "PACARI",
  "SJF Ventures",
  "MaCher USA",
  "Praxis Consulting Group",
  "Dr. Bronner's",
  "Arctic Solar Ventures Corporation",
  "Impact Square",
  "Social Impact Strategies Group",
  "Singularity University",
  "indieDwell Inc",
  "Benedictus Media Buying & Planning Pty Ltd",
  "Dhana Inc.",
  "AMATA",
  "Amalgamated Bank",
  "Cultivating Capital",
  "Last Triumph",
  "Fetzer Vineyards",
  "EQ Investors",
  "Forward Philanthropy",
  "Chandos Construction",
  "100km Foods Inc.",
  "Junxion Strategy",
  "The Urdang Academy",
  "Jim's Organic Coffee",
  "Renewal Care Partners",
  "Cabot Creamery Co-operative",
  "Spring Bank",
  "Full Circle Home",
  "Yerdle",
  "KNOWN SUPPLY",
  "Caravela Coffee",
  "Transcend, The Fearless Company",
  "Active Impact Investments",
  "One Village Coffee LLC",
  "Olivelink Healthcare",
  "Patagonia Works",
  "Superior Switchel Company, LLC",
  "Business Development Bank of Canada",
  "Diva International Inc.",
  "Animikii",
  "Hair,Head & Heart",
  "Leesa Sleep",
  "Jetty",
  "Kazidomi",
  "DDJ&",
  "We First",
  "Bensimon Center",
  "Social(k)",
  "Looptworks",
  "Sundial Brands, LLC",
  "Vine Ride",
  "Indigenous Pact PBC, Inc",
  "Copper8",
  "Education for Good CIC Ltd.",
  "SolarNow",
  "Flynner Homes",
  "Feynman Group, Inc.",
  "Cook Trading Ltd",
  "BetterWorld Telecom",
  "Electrygen Pty Ltd Trading as Petawatt",
  "JoJo Maman Bebe",
  "MVA Trading SA",
  "Wakami",
  "Dog and Bone Pty Ltd",
  "Pasticceria Filippi Srl Società Benefit",
  "GLASSY FILMS",
  "Abafoods",
  "RetailOasis",
  "Kuli Kuli",
  "Neometro",
  "Marmalade Fish",
  "Asher International eco-Health Enterprises Inc.",
  "INFINITAS International Co. Ltd.",
  "River Capital",
  "Sprout Ventures PTY LTD",
  "Danone Waters Spain",
  "Spotlight:Girls",
  "Genashtim Innovative Learning Pte Ltd",
  "Morris Recruiting & Consulting",
  "Tillak",
  "AMS Fulfillment",
  "Whiteboard",
  "Veterinary Specialty Center",
  "NationSwell",
  "Northwest Capital Management, Inc.",
  "Lyv Life Inc.",
  "SpringFour, Inc.",
  "CohenTaylor",
  "Upstreet Craft Brewing",
  "Evolution Marketing",
  "coLAB, Inc.",
  "Flow",
  "Fishpond Inc.",
  "Firespring",
  "Bazzani Building Company",
  ".org/advisors",
  "Guild Education",
  "ALL GREEN RECYCLING INC.",
  "i.d.e.a.",
  "Blue Marble Ice Cream, LLC",
  "North Berkeley Investment Partners",
  "American Prison Data Systems, PBC",
  "Boston Organics",
  "Change Catalyst",
  "Bixbee",
  "Roundpeg Benefit LLC",
  "Staach",
  "Rubicon Bakers",
  "Innovation for People",
  "World Leadership School",
  "Crave Fishbar",
  "Beautycounter",
  "Biomimicry 3.8",
  "Allbirds, Inc.",
  "Lancaster Works at ASSETS, LLC.",
  "Happy Family Organics",
  "Mother E",
  "Commons Company",
  "Pono Home",
  "Advanced Metrics",
  "Lantinga Vita Inc.",
  "The Vegan Broker Inc.",
  "Commonhouse Ales",
  "Vanderburgh House",
  "Scoutcomms, Inc.",
  "Chickapea",
  "MIO",
  "1908 Brands",
  "Save On Meats",
  "Archi's Acres",
  "Portola Creek Capital",
  "Symplicity Designs Inc",
  "Green Living Enterprises",
  "Tony's Chocolonely",
  "Shifting Patterns Consulting",
  "Bombas",
  "The National Society of Leadership and Success",
  "Business Culture Consultants",
  "Alaya (www.alaya.com.br)",
  "Dolium Bodega Subterranea",
  "Ellevate Network",
  "New Leaf Paper",
  "Ramp Communications Inc.",
  "REthink Development",
  "Encanto Jewels",
  "Whitney Hess",
  "Revision Energy Inc",
  "New Seasons Market",
  "B'more Organic",
  "NativeEnergy, a Public Benefit Corporation",
  "People Against Dirty",
  "Wicked Ideas Media Inc",
  "Kosmenko & Co.",
  "Techstars",
  "Habitus Incorporated",
  "Hop Compost",
  "Northwest Permanente",
  "Annona Sustainable Investments BV",
  "Bodhi Surf + Yoga",
  "TreeTop Commons LLC",
  "Danone Canada",
  "Authenticitys Experiences SL",
  "Lemonade, Inc.",
  "Someone Somewhere",
  "Trico Homes",
  "Natura Cosméticos SA",
  "OlyKraut",
  "Late",
  "Peeled Snacks",
  "ORGANIZZARE ITALIA S.R.L. S.B. UNIPERSONALE",
  "COINNOVAR",
  "NATIVA Srl SB",
  "Inspiring Capital",
  "Rubicon Global",
  "Coffee By Design",
  "Taos Ski Valley, Inc.",
  "EQOSPHERE SAS",
  "Berrett-Koehler Publishers",
  "Obrigado",
  "Swink Webservices",
  "TerraCarbon",
  "Fairphone",
  "Pure Ground Ingredients",
  "Magnus",
  "LED Inspire | WATT and FLUX",
  "TAZE KURU GIDA INC",
  "Participant Media",
  "BlueRock",
  "Squareweave",
  "Practical Energy Solutions",
  "evelina eco events",
  "Narrative Food",
  "Meow Wolf",
  "Divine Chocolate Ltd",
  "Lake Champlain Chocolates",
  "OMISTA Credit Union",
  "Libro Credit Union Limited",
  "Inspired Ventures",
  "Ripple Foods, PBC",
  "Inspired Adventures",
  "Patton Valley Vineyard",
  "Schaffer&Combs",
  "Third Sun Solar",
  "Starboard",
  "GreenStep Solutions Inc.",
  "Numi Organic Tea",
  "Textbooks for Change",
  "FARMACIA A. COLUTTA DELLA DOTT.SSA ANTONELLA COLUTTA & C.",
  "Keap",
  "Grove Collaborative Inc.",
  "Danone UK",
  "Aguas Danone Argentina",
  "Goodwings",
  "earthy, LLC.",
  "CasaCo",
  "Cotopaxi",
  "Good-Loop",
  "Danone Iberia",
  "ALTERFIN",
  "ETT spa",
  "Fit 4 Dance",
  "PRANA",
  "Dr. Hauschka Skin Care, Inc.",
  "Garden of Life, LLC",
  "NEEV",
  "A to Z Wineworks",
  "INDIGENOUS Impact Fashion",
  "Pinnacle Commercial Interiors",
  "Our Community Pty Ltd",
  "OrgBetter",
  "OneSeventeen Media, PBC",
  "Fairware Promotional Products",
  "Dumbo Feather",
  "Better Future",
  "Hobé Hosokawa Marketing",
  "Eco-Bags Products",
  "Carbon Analytics",
  "OpenBook.Works",
  "B&L évolution",
  "Code For All",
  "Purpose",
  "Urban Remedy",
  "All Good",
  "SES Consulting",
  "Strozzi Institute",
  "Motherlove Herbal Company",
  "GrinCraft",
  "World Centric",
  "Green Circle Salons",
  "Namaste Solar",
  "Seventh Generation",
  "South Mountain Company, Inc.",
  "Southern Energy Management",
  "Parque del Recuerdo",
  "REfficient Inc.",
  "Artfinder",
  "Exygy",
  "Paintbox Catering and Bistro Inc.",
  "Emzingo",
  "Playing For Change",
  "Sun Light & Power",
  "Fiix",
  "Vitarock",
  "Latinlingua",
  "Ozery Bakery",
  "Pure Strategies",
  "Seed Systems, Inc",
  "Vaya Finserv Private Limited",
  "Stonyfield Farm",
  "Organic Ocean Seafood Inc.",
  "JB Media Group, LLC",
  "GreenSpace Brands Inc",
  "CauseLabs",
  "Carbon Credit Capital LLC",
  "Mills Office Productivity",
  "Vista Global Coaching & Consulting LLC",
  "Beneficial State Bank",
  "Genus Capital Management Inc.",
  "FFunction",
  "Dunsky Energy Consulting",
  "Common Good Solutions",
  "BottleDream",
  "Bi-Rite Market",
  "Conscious Brands",
  "Torani",
  "Green Retirement, Inc.",
  "Hipocampus Centros de Aprendizaje",
  "Left Coast Naturals",
  "Eileen Fisher, Inc.",
  "Image Outfitters, Inc.",
  "Mad Fish Digital",
  "MMercer Consulting",
  "Ian Martin Group",
  "Colibri Digital Marketing",
  "Fig Industries",
  "Karner Blue Capital, LLC",
  "StreetwiZe",
  "Advanced Enviro Systems",
  "New Belgium Brewing Co, Inc.",
  "Sweet Livity LLC",
  "850zip",
  "TOMS",
  "Flowers for Dreams",
  "PeaceWorks Technology Solutions",
  "UTOPIES",
  "Green Dinosaur, Inc.",
  "Ecodeo",
  "Nature et Decouvertes",
  "Inspire",
  "PIE Strategy Limited",
  "Vox Capital",
  "Merry Year Social Company (MYSC)",
  "Local Peoples",
  "Beam Australia",
  "Clearpoint Counsel Pty Ltd",
  "Vital Consult",
  "The School of Life Australia",
  "Underground Communications",
  "Venturetec Group",
  "Ethical Property Australia Pty Ltd",
  "Intopia",
  "nu-tility",
  "Emma & Tom's",
  "Seated Massage",
  "OORR",
  "O'Connells OBM",
  "Grow Good",
  "acidlabs",
  "Hothouse Design",
  "Currie Communications",
  "Forward Thinking Design",
  "Adventure Junky",
  "Arnsdorf",
  "Murray River Organics Ltd",
  "BEAR",
  "Think Impact",
  "BDCU Alliance Bank",
  "Mandalay Bay Investments Pty Ltd",
  "Huddle",
  "Kester Black",
  "Rankin Business Lawyers",
  "Solar Analytics",
  "Little Yellow Bird",
  "Landserv Pty Ltd",
  "August",
  "Silver Chef",
  "Raine & Makin",
  "Business Growth Strategies",
  "The Social Deck",
  "MiHaven",
  "Mustard Seed Podiatry",
  "Mkt. Communications",
  "One Roof Women Pty Ltd",
  "BRM Projects",
  "Wealth Enhancers",
  "Eagle Direct Ltd (Eagle Group)",
  "Hatched",
  "Fair Food Forager",
  "TeleMed Health Services",
  "Mama Maya Pty Ltd",
  "Future Friendly",
  "Foresters Group",
  "AV1 Pty Ltd",
  "Good Business Matters",
  "Blacksmith Limited",
  "Etiko Pty Ltd",
  "Enviro-Mark Solutions",
  "NutriSoil Pty Ltd",
  "Your Call Whistleblowing Solutions",
  "Nation Partners",
  "Verso Learning",
  "SGS Economics and Planning",
  "Global Leadership Foundation",
  "Digital Business Hub",
  "Vollie",
  "New Forests",
  "Happy Spaces",
  "Monochrome Coffee Co.",
  "The Sponge",
  "Digital Storytellers",
  "Adara Advisors",
  "Digital Operative",
  "Salvos Legal",
  "Community Services.Net Pty Ltd",
  "Teak Yew",
  "Marque Lawyers",
  "Fitzgerald Frisby Landscape Architecture",
  "BioBalance Ltd",
  "Red Gum BBQ",
  "Collective Intelligence",
  "NGNY (Ngakkan Nyaagu)",
  "Aither Pty Ltd",
  "Ethinvest",
  "Arktisma",
  "Small Giants Australia",
  "Marlin Communications",
  "Handknits Pty Ltd",
  "Montville Coffee Pty Ltd",
  "TANK Pty Ltd",
  "eWater Systems Pty Ltd",
  "4 Pines Brewing Company",
  "Hit 100",
  "Good Environmental Choice Australia (GECA)",
  "Community Sector Banking",
  "Future Superannuation Group",
  "Right Lane Consulting Pty Ltd",
  "The Farm Collective",
  "Grow Your Mind",
  "RBK Advisory",
  "B cubed Management Consultants Pty Ltd",
  "Brown Bread Ltd",
  "Land & Water Consulting",
  "Vivid CD (inc GlassyAnt)",
  "Banqer",
  "Reho Travel",
  "Sawmill Brewery",
  "Edge Environment",
  "Flora & Fauna",
  "memobottle Pty Ltd",
  "Hitnet",
  "Presync",
  "Edumazing",
  "ByFusion PBC",
  "Ndevr Environmental",
  "Onya Life",
  "Peoples Coffee Limited",
  "Cube Group",
  "Mentorloop",
  "Vivid Technology",
  "WE-AR",
  "Hepburn Wind",
  "Disruptive Media",
  "Agency",
  "Jasper Coffee",
  "Hoyne",
  "Montcalm TCR LLC",
  "Pymwymic",
  "Zelfstroom B.V.",
  "Imfusio",
  "BIKOnsulting, S. Coop.",
  "Ben and Jerry's",
  "Investeco Capital",
  "Johnstaff Projects Pty Ltd",
  "Barnana",
  "Australian Ethical Investment",
  "Fors Marsh Group LLC",
  "gDiapers",
  "Kindred Credit Union",
  "Optel Group",
  "Gaia Herbs",
  "PROVOC",
  "This is L. Inc.",
  "Yogi Tea U.S.",
  "First Respond 第一反应®",
  "Gibbons Whistler",
  "Ella's Kitchen UK",
  "Chehalem Winery",
  "BSW Wealth Partners LLC",
  "GREEN GOO",
  "Bridgetown Natural Foods",
  "Towerbrook Capital Partners L.P.",
  "Assurity Life Insurance Company",
  "Blue Garnet",
  "Alima Cosmetics, Inc.",
  "BioGo, GBC",
  "Stumptown Coffee Roasters",
  "P.L.A.Y. Pet Lifestyle and You Inc.",
  "3 Phases Renewables",
  "Culinary Collective",
  "The CAPROCK Group",
  "Proyecto Agua Segura",
  "AllCare Health, Inc.",
  "Heather Paulsen Consulting",
  "Psicometrix",
  "Wanderlust",
  "Help Scout",
  "Grand Central Bakery",
  "Lulu Press, Inc.",
  "Ocean Brands",
  "Pozible",
  "Stone & Wood Brewing Company",
  "Beyond Bank Australia",
  "Who Gives A Crap",
  "Culture Amp",
  "Nutricare Pty Ltd",
  "Triple P International Pty Ltd",
  "Ironbark Sustainability",
  "StartSomeGood",
  "Redvespa",
  "Winya Indigenous Furniture",
  "361 Degrees Strategic Engagement Services",
  "Munch Crunch Organics",
  "Duffle & Co",
  "thinkstep Australasia",
  "Dan the Man Cooking",
  "Eat Me Chutneys",
  "Core Projects",
  "Sienna Byron Bay Pty Ltd",
  "Food Connect",
  "Biome Eco Stores",
  "Seed Consulting Services Pty Ltd",
  "Hub Australia",
  "BioPak",
  "TOM Organic",
  "Cooperative Home Care Associates (CHCA)",
  "DUCA Financial Services Credit Union",
  "Danone Waters of America, Inc.",
  "Runa",
  "RALLY",
  "BEE'S WRAP",
  "TBL Services Ltd",
  "Cove Continuity Advisors Inc",
  "The House",
  "Adara Partners (Australia) Pty Limited",
  "Future State",
  "Westwood International",
  "Q&A",
  "Plataforma Áurea",
  "SustainAbility",
  "Kin&Co",
  "SingularityU Nordic",
  "Matteria",
  "Pares | Strategy & Development | Estratégia & Desenvolvimento",
  "Kaya Impacto",
  "Atuação no Mundo - Projetos de Mobilização e Comunicação",
  "Sweetmans & Partners",
  "Simanye",
  "twentyfifty Ltd",
  "PATHFINDER",
  "Kirkman Company",
  "Damasco",
  "August Public Inc",
  "Pelorus Consulting",
  "Measure Meant",
  "Pineapple Sustainable Partnerships",
  "Undercover Rose",
  "Karisimbi Business Partners Ltd Rwanda",
  "TCG, Inc.",
  "Trebuchet Group International LLC",
  "Sylvain Labs, Inc",
  "Sustainable Business Consulting (sbclimited.org)",
  "Shamaym",
  "in3citi S.A. Inovações, Investimentos e Instituições",
  "Paradox Consulting Partners, LLC",
  "Lex Ultima",
  "Grupo Advance",
  "WILLY Consultants Co., Ltd",
  "IQbusiness",
  "Edward James Consulting Ltd.",
  "Credo",
  "Broadgreen Solutions",
  "New Angles",
  "do good well consulting LLC",
  "Focus Lab srl",
  "Kinesis",
  "Business Fights Poverty",
  "Transformation Catalyst Corp.",
  "Twelve Winds Consulting",
  "Tricordant",
  "COESIO",
  "Inclusiva Consultores",
  "Aquatro Cultura de Impacto",
  "Consilio",
  "People & Partners S.A.",
  "TARGET-DDI",
  "Geco",
  "Givily",
  "dutch",
  "AlmaNatura",
  "ProQualitas",
  "WonderWorks Consulting",
  "HUMIND",
  "StepBeyond",
  "VIANOVA, Inc.",
  "Audacious Inquiry",
  "Coherence Collaborative",
  "Altman Partners",
  "ECrowd!",
  "EnTerrenoSocial",
  "Valle y Pampa Peru",
  "eosis",
  "MOV INVESTIMENTOS Ltda",
  "eCycle",
  "CBPAK Tecnologia S/A",
  "Ecotone Software Consulting Inc.",
  "IMPAQTO",
  "Daterra Atividades Rurais",
  "Mac's List, Inc.",
  "WeBuild (www.webuild.city)",
  "Innpact",
  "Good Talent",
  "Cause Strategy Partners, LLC",
  "Springboard Education in America LLC",
  "SiembraViva",
  "ECOSOCIAL CONSULTORIA EM DESENVOLVIMENTO HUMANO E ORGANIZACIONAL  LTDA.",
  "Perform Green Limited",
  "SoFine Food",
  "ViRTUS",
  "S360 Sustainability Services",
  "Super Humane",
  "SUBENCO div. Euro Brand Management GmbH",
  "The Dandavati Group",
  "Rescue Agency",
  "BSD Consulting",
  "Athleta",
  "Vista Caballo",
  "BlueWave Solar",
  "CIANO Alimentos Sustentáveis Ltda.",
  "Perlman and Perlman, LLP",
  "Goodpoint",
  "Good Day Girl",
  "Enablr Pty Limited",
  "Miei Fiori",
  "Naomi Arnold",
  "Kusaga Athletic",
  "James&Co (Australia) Pty Ltd",
  "Management Resources",
  "Instituto Yiesia",
  "XPLANE",
  "Sustain in Time Global AB",
  "Medora Ventures",
  "Endeva",
  "Yo Elijo",
  "Sunshine Nut Company",
  "Ellio Inc",
  "Innate Motion",
  "Women in Management",
  "Flip Labs",
  "BR-ND | Emotive Transformers",
  "Sair da Casca",
  "Fibra Design Sustentável/ MateriaBrasil",
  "Organicos Brita",
  "Via Gutenberg",
  "3vectores",
  "Sustainability Advantage",
  "Celilo Group Media",
  "GEDES",
  "Sinergia Positiva",
  "CreativeLab S.A.S",
  "Almaciguera Consultora",
  "The Change Collective",
  "Living Alive",
  "5T Sports Group",
  "GA Circular",
  "Ever Better, PBC",
  "Green Libros",
  "Din4mo",
  "Sustenta Consultores SpA",
  "Climate Resilience Consulting",
  "Context Partners",
  "One Stone",
  "Moementum, Inc",
  "Ematris",
  "Gulliver",
  "Valor CSR",
  "Gem Consulting Solutions, llc",
  "Shoremount",
  "TiER1 Performance Solutions",
  "idgroup",
  "KOGA S.A.",
  "NOW Magazine",
  "Nectar Consulting Inc",
  "Talsom",
  "Outside Inc.",
  "Banyan Botanicals",
  "Eleek Incorporated",
  "Schoolzilla PBC",
  "Sales Srl",
  "High Park Brewery",
  "Traditional Medicinals",
  "GreenPlanet Bio-Fuels",
  "WholeTrees, LLC",
  "Symington Family Estates",
  "Fig Loans",
  "Proyecta",
  "Clean Solar",
  "Rebel Kitchen",
  "Bridges Fund Management",
  "Come True Social Enterprise Co., Ltd.",
  "The ReFrame Financial Group Inc.",
  "OMPLIM GESTIO I EDIFICACIO RESPONSABLE SL",
  "Grassriots",
  "GreenSavers",
  "Fully",
  "Kent Employment Law",
  "Two Dudes Painting Company",
  "Lácteos Tronador",
  "GloryBee",
  "EFM",
  "Noto Group",
  "The Cheeky Panda",
  "Simplicity Works Benefit LLC",
  "LVK Global",
  "Diagonal",
  "Higher Legal",
  "GreenCollar",
  "northraine",
  "Sprout Coffee",
  "Thread Harvest",
  "Maths Pathway",
  "Senversa",
  "Wattle Partners",
  "TheStoryBoxes Pty Ltd",
  "Tickbox",
  "Green Moves Australia",
  "Spark Strategy",
  "Be Collective",
  "Bellroy",
  "Factors Group Australia",
  "The Talent Connective",
  "Green2View Pty Limited",
  "Pro Bono Australia",
  "U Ethical",
  "Pangolin Associates",
  "23 Degrees Coffee Roasters",
  "Pablo & Rustys Pty Ltd",
  "KeepCup",
  "Today",
  "Adopt & Embrace",
  "The Space Agency",
  "Little Innoscents",
  "Triskel Coaching Consultancy",
  "Thirst Studios",
  "Outland Denim",
  "China Australia Millennial Project",
  "CIRCLE Alliance Bank",
  "Musketeers",
  "Align Work Health",
  "Dunn & Hillam Architects",
  "BizBuddyHub",
  "Point Advisory Pty Ltd",
  "Portable",
  "International Volunteer HQ (IVHQ)",
  "Latrobe Valley Bus Lines P/L",
  "Sharesies",
  "Ethique",
  "Brightgreen",
  "Republic of Everyone",
  "Australia and New Zealand Recycling Platform",
  "Humanitarian Advisory Group",
  "Dynamic4",
  "Emaho Trees",
  "Honest to Goodness",
  "i=Change",
  "DrawHistory",
  "Spacecubed",
  "Talent Nation",
  "Sendle",
  "Carolyn Tate & Co.",
  "Impact Investment Group",
  "Atticus Lawyers Pty Ltd",
  "Cherished Pets Pty Ltd",
  "Quiip",
  "ClarkeHopkinsClarke Architects",
  "Elkie & Ark",
  "Catalyser",
  "Capire Consulting Group",
  "5 Degrees Property Group",
  "Inventium",
  "Freerange Future",
  "Republica Organic",
  "Social Enterprise Finance Australia Ltd",
  "Mud Environmental",
  "BWD Strategic",
  "Sample Coffee Roasters Pty Ltd",
  "ARA Consultants Limited",
  "Aspen Medical",
  "All The Wild Roses Pty Limited",
  "Energy for the People",
  "CoGo - Connecting Good",
  "AWA Alliance Bank",
  "Anywise Consulting Pty Ltd",
  "Koskela Pty Ltd",
  "Koala",
  "GlamCorner",
  "Light Warrior",
  "Flow Hive (BeeInventive Pty Ltd)",
  "Metagenics Australia",
  "Lantern Legal Group",
  "Education Changemakers",
  "Recycle Track Systems, Inc.",
  "Alaya (alayagood.com)",
  "Cirklo",
  "Out Leadership",
  "Danone Waters Germany",
  "Bridge Chile",
  "Orchestrate Technologies",
  "Boly:Welch",
  "TheDive GmbH",
  "4th Bin Inc.",
  "Idealist Consulting",
  "Altvia Solutions, LLC",
  "FIBUR GmbH",
  "GOOD Media Group",
  "UpSpring",
  "Sustainable Growth Associates GmbH",
  "NorthFork Financial, LLC",
  "Social Impactrip, Lda",
  "Pixel Parlor",
  "ZANLORENZI BEBIDAS",
  "CleanChoice Energy",
  "New Kind",
  "brew advisors",
  "Cropsticks by Cropmade",
  "Metropolitan Group",
  "Rhino Foods",
  "TUX",
  "Prosper for Purpose LLC",
  "Ernest Cider Co. LTD.",
  "Heller Consulting",
  "Techtonic",
  "Jeni's Splendid Ice Creams",
  "ANDES EXPRESS SAC",
  "CODE BRAND S.A.C.",
  "hösėg",
  "Energe SA",
  "Bullfrog Power",
  "SNW Asset Management",
  "Daktari",
  "Wicked Joe Organic Coffees",
  "Coast Capital Savings",
  "Council Fire LLC",
  "Les 2 Vaches",
  "Sherpa Foods, SPC",
  "Château Maris",
  "Assimoco S.p.A.",
  "Maria Farinha Filmes",
  "Sustainable Business Consulting (www.sustainablebizconsulting.com)",
  "Connective Impact",
  "Gardener's Supply Company",
  "GEXSI",
  "NISECorp S.E. Co.,Ltd.",
  "Singbee",
  "Conser Invest",
  "Geek Girl Tech",
  "Impact Hub srl (Impact Hub Milano)",
  "Green City Growers",
  "Image Relay",
  "Damiano Spa",
  "PerMicro",
  "Lemon Tri",
  "NewForesight Holding B.V.",
  "Salcheto",
  "PatteBlanche",
  "Esterhazy Wein GmbH",
  "Zordan S.r.l. sb",
  "SOCAR",
  "data.world, Inc.",
  "Immaculate Cleaning Services",
  "Paige Wolf Media & Public Relations",
  "Imago, LLC",
  "Blue Dot Advocates, PBC",
  "Good for Business",
  "Clover Sonoma",
  "The Zen Life Center, Inc.",
  "Mangrove Web Development",
  "Revivn",
  "Spotlight Solar",
  "BarberGale",
  "Dev Equity, LLC",
  "Moon Valley Organics",
  "King Arthur Flour Company",
  "Vermilion Inc.",
  "Kria",
  "Greenheart Business Consulting Ltd",
  "Sora Finance",
  "Stone Soup Consulting",
  "IN GOOD CO",
  "Bright Concept",
  "Okena",
  "Y Scouts",
  "Cambridge Naturals",
  "Yin Yang Naturals",
  "Raven + Lily",
  "Strugatz Ventures, Inc.",
  "AguiaLabs",
  "Liatin SA (Impulso Creativo)",
  "Vanessa Montoro",
  "Carlotas",
  "MacKay CEO Forums",
  "Sector 3 - Consultoria de Gestão",
  "Nodo Chile",
  "Next Street",
  "StoryStudio Chicago",
  "Meaningful Organizational Design, Inc.",
  "By Connection Consultoria e Treinamento Ltda",
  "SecondMuse",
  "Bartle",
  "Te Quiero Verde",
  "Revolution Foods",
  "Milepost Consulting",
  "SCP",
  "Lily's Kitchen",
  "Beau's All Natural Brewing Company, Ltd.",
  "Better Places",
  "N&B Srl",
  "MindFull",
  "Porta Hermanos",
  "OLLY",
  "BrandIQ",
  "Caddis PC",
  "Mayfly Outdoors",
  "Aunt Bertha, Inc.",
  "Houwzer",
  "LIFT Economy",
  "kubo financiero",
  "Shared Value Solutions",
  "ILUMEXICO",
  "BlueAvocado Co.",
  "Salt Spring Coffee",
  "ecoRobotix SA",
  "Love Bottle",
  "Próxima",
  "Sno-Isle Food Co-op",
  "Goodpin Inc.",
  "Armonia LLC",
  "Mal Warwick Donordigital",
  "Impact Makers, Inc.",
  "AltSchool, PBC",
  "NewInc Construtora",
  "Encore Renewable Energy",
  "KeHE",
  "humbition",
  "Re-Vive",
  "Active Health Group",
  "P2",
  "Delicious & Sons",
  "Service Vending srl Società Benefit",
  "i-propeller",
  "Wijngoed en Zorghoeve de Reestlandhoeve v.o.f.",
  "The Builders Fund",
  "Salt Palm Development",
  "Big Path Capital",
  "LITO REVERBERI DI REVERBERI ..",
  "Generous Minds",
  "Pearl Consulting",
  "Coffee Circle",
  "Broughton Consulting, LLC",
  "Lunapads",
  "Amicus Solar Cooperative",
  "share",
  "HigherRing",
  "Sea Witch Botanicals",
  "Creative Chi Inc",
  "4D Content English",
  "Stasher, Inc.",
  "Seams To Fit",
  "National Co+op Grocers",
  "YIKES, Inc",
  "Neil Kelly Company",
  "Freesia Company Limited",
  "BioClea Cleaning Ecosostenibili Srl SB",
  "Lygo",
  "HELIOZ",
  "ISOS Group, Inc.",
  "Talents4Good GmbH",
  "Hootsuite",
  "Donegood, PBC",
  "ResolutionCare Network",
  "Bluestone Life",
  "Sulilab SpA",
  "PixelSpoke",
  "Roots for Sustainability (R4S)",
  "ChiloteShoes",
  "African Bronze Honey Company Limited",
  "The Road Less Traveled",
  "Homeboy Recycling",
  "Box Latch Products - Made by Eco-Latch Systems LLC",
  "Elidria Srl SB",
  "ROAR for Good LLC",
  "armstrong y asociados",
  "Down to Earth Market",
  "Indosole, LLC",
  "Dimagi, Inc.",
  "Climate Advisers",
  "CoLab Cooperative",
  "aWhere, Inc.",
  "Solar Works",
  "Oliberte Limited",
  "Zevin Asset Management",
  "Goodmans Interior Structures",
  "TriCiclos Brasil",
  "Organic Planet LLC",
  "Ediciones SM Chile",
  "IF",
  "Granos Andinos de Colombia S.A.S",
  "BioPlaza SAS",
  "SEQUIL Systems Inc.",
  "Comercial Epullen Ltda.",
  "stok",
  "Insamar",
  "Message Agency",
  "One World Play Project",
  "Sunrise Banks",
  "AVANT Group LLC",
  "Eco Lips, Inc.",
  "Namidabashi Lab.",
  "MIXT",
  "Deetken Impact",
  "Floyd Snider",
  "Giving Assistant, Inc.",
  "Kotn",
  "Rainbow Collection",
  "XENSHA",
  "Caspian Impact Investment Adviser Private Limited",
  "PinotBleu",
  "Eat Well Global Inc.",
  "Organic India USA",
  "Straightup Solar, LLC",
  "Brattleboro Savings & Loan",
  "Beyond Green Sustainable Food Partners",
  "Imani Development",
  "Maker srl",
  "OBA SAS",
  "The Wave (HK) Corporation Limited",
  "Inherent Group, LP",
  "3Degrees Group Inc.",
  "Leap",
  "CoolCap Limited",
  "The Earth Group",
  "Sensiba San Filippo LLP",
  "Pete & Gerry's Organics, LLC",
  "SunCommon",
  "Danone Egypt",
  "ChicoBag Company",
  "Bolder Industries",
  "Network for Good",
  "Beanfields Inc.",
  "cmv Consulting",
  "THE SKATEROOM",
  "RE-LAB",
  "OBERLAND",
  "American College of Healthcare Sciences",
  "Hopemakers",
  "Mightybytes, Inc.",
  "Global Round Table Leadership",
  "DOJO4",
  "Halcyon Consulting Group",
  "Abacus Wealth Partners, LLC",
  "Crazy Richard's Peanut Butter Company",
  "Common Interests",
  "Happy Valley Meat Company",
  "Social Impact Advisors",
  "WAMI Srl SB",
  "Goldmann & Partners Srl",
  "Enviu",
  "Sleeping Lady Resort",
  "City Light Capital",
  "Natural Systems Utilities",
  "Red212",
  "Desert Farms, Inc.",
  "Cubreme",
  "Recycle-A-Textbook.com",
  "Bigelow Tea",
  "Impossible Labs",
  "Opticos Design, Inc.",
  "Fratelli Carli SpA",
  "Savannah Consulting",
  "Vera Solutions, Benefit LLC",
  "Success Rehabilitation",
  "Goodr",
  "einhorn",
  "Travois",
  "Montagne Alternative",
  "Coates Kokes",
  "Danone Manifesto Ventures",
  "Strategy Arts",
  "Impact Hub Amsterdam",
  "Entegrit",
  "AoSA inc",
  "Seal The Seasons",
  "Bureo Inc",
  "Culshaw and Co",
  "boxgreen",
  "General Bio",
  "Traction on Demand",
  "The Redwoods Group",
  "Alessi s.p.a.",
  "Emmy's Organics",
  "MilkCrate",
  "PARADISI SRL",
  "CORE Foods",
  "ThinkShout, Inc",
  "GoodPop",
  "North Coast Brewing Co., Inc.",
  "Fiasco Gelato",
  "Reitmeier",
  "Sympatex Technologies GmbH",
  "Bohlsen Group",
  "Hood To Coast Relay",
  "AIR coop",
  "Rally Assets",
  "Abreu Advogados",
  "Lumo",
  "Steelter",
  "BE MORE Inc.",
  "MagicTomato",
  "Solibrium",
  "Element Five",
  "PV Squared",
  "Essential Living Foods, Inc.",
  "ImpactAdvisor LLC",
  "LOACOM",
  "HQ Raleigh",
  "Digitopia",
  "Forster Communications",
  "Cool Energy, Inc.",
  "Agents and Corporations, Inc. (trading as IncNow)",
  "Dharma Merchant Services",
  "Sustainable Law Group, P.C.",
  "Public News Service",
  "Genuine Health",
  "E-180, inc",
  "innocent Drinks",
  "Mascoma Bank",
  "Good Food for Good Inc.",
  "Verdical Group",
  "Luke's Lobster",
  "Cuento de Luz",
  "ZG Communications Inc.",
  "Tom's of Maine",
  "Telecom Development Company Afghanistan Ltd. (Roshan)",
  "Aggelos",
  "Perlage winery",
  "Vital Farms",
  "UncommonGoods",
  "3P Partners, Inc.",
  "AeroFarms",
  "Pacific Collective Real Estate",
  "Foundry Group",
  "Burnham Benefits Insurance Services",
  "Nossa Familia Coffee",
  "De Micheli Lanciani Motta Psicologi del Lavoro Associati",
  "Ocean Observations AB",
  "Salazar Landscaping",
  "Watts Battery Ltd",
  "Kozm Inc.",
  "Bruggink & van der Velden Advocaten Belastingadviseurs BV",
  "Evergreen Lodge",
  "Yoni",
  "African Clean Energy",
  "Nextview",
  "THE PLAYMAKERS",
  "La Marchigiana",
  "Daycos, Inc",
  "Green Mountain Power",
  "The Ariel Group LLC",
  "Boston Common Asset Management LLC",
  "Manoverboard Inc.",
  "Natural Investments LLC",
  "Re:Vision Architecture",
  "High Impact Financial Analysis, LLC",
  "Align Impact",
  "Noble Manhattan Coaching Americas",
  "Wefunder",
  "ZEGO",
  "Flow Office Wisdom",
  "Roadhouse Brewing Company, LLC",
  "ECOTIERRA",
  "MGov",
  "Asap - Perfomance do Conhecimento",
  "Flavia Aranha Comércio e Confecção EIRELI - ME",
  "Casa do Futuro",
  "Insecta Shoes",
  "AMMA Chocolate",
  "Move Avaliação e Estratégia em Desenvolvimento Social",
  "Decah",
  "Asta Corp Produtos Sustentaveis Ltda",
  "Meu Copo Eco",
  "PAPEL SEMENTE IND E COMERCIO LTDA",
  "Eco Panplas",
  "Extensio",
  "RDA Renting SA",
  "Las Tacuaras S.A.",
  "Intelligent Eco Solutions SpA",
  "ENVACO S.A",
  "Pantys",
  "NXTP Labs",
  "Grupo Basicos SA",
  "done!",
  "Ediciones SM SAC",
  "Editora Voo",
  "EMINLAGA SRL-MAMUT",
  "Simbiose Social",
  "Mujeres que Emprenden",
  "Balloon Latam",
  "Marketgreen",
  "Red Apis",
  "VerdeActivo",
  "Nice Dog",
  "Veomás Coaching",
  "Degraf SpA",
  "Emprediem",
  "Cumplo Chile S.A.",
  "Contreebute",
  "FINAE SAPI DE CV SOFOM ENR",
  "Echale a Tu Casa",
  "NOW Transforming Hospitality GmbH",
  "Physee",
  "OMAL S.p.A",
  "Davidson Consulting France & Switzerland",
  "Bottega filosofica srl",
  "Lifesaver Power",
  "CEF Publishing s.r.l.",
  "OmniCert Umweltgutachter GmbH",
  "Zoku",
  "24Slides",
  "Green Element Limited",
  "Earthbound Farm",
  "Sokol Blosser Winery",
  "ME to WE",
  "Animana",
  "El Viaje de Odiseo",
  "Reciclarg S.A.",
  "Quinn & Partners Inc.",
  "West Paw, Inc.",
  "Impact Seed",
  "Red Megacentro",
  "HOJAVERDE CIA. LTDA.",
  "Colegio Kopernikus",
  "SEMPLI S.A.S",
  "Sylvie Boks S de RL de CV",
  "FEMSOLUTIONS SAS",
  "Fixit",
  "Agricola Sauco SpA",
  "Biourbanismo - By Botanik",
  "Neurônio Ativação de Negócios e Causas",
  "Revitaliza Consultores",
  "Elementos Argentinos",
  "Pura",
  "PAPA",
  "UNITECH S.A.",
  "Jaguar",
  "PLATA SAC - Global Beauty CORP",
  "TINGUA",
  "Win & Winnow Language Services",
  "Wongtschowski & Zanotta Advogados",
  "Biogreen",
  "HG ingeniería y construcciones s.a.s",
  "Doble Impacto",
  "Editora MOL",
  "Ciudad Luz",
  "Comaco",
  "IRCA SRL",
  "Comunicación Puente LTDA",
  "Pacific Nut Company Chile S.A",
  "Finaktiva",
  "Iconosur",
  "HILANA",
  "Rentcars Ltda",
  "Mboja'o",
  "Indeleble Social",
  "ÓBOLO Chocolate SpA",
  "Entelékia / Integrow",
  "TEVA",
  "Olivia Saladas",
  "Textiles y Confecciones Eco Sustentables SpA",
  "Creer Hacer",
  "YOUHUB COWORK",
  "Joya Plástica",
  "Choucair Testing S.A",
  "Kiron SPA",
  "Limite Vertical",
  "BILD",
  "Servioptica",
  "Biogar",
  "APP Chile",
  "ME Motivador de Experiencias",
  "Asesorías y Servicios Kyklos Spa.",
  "VerdeAgua Hidroponia",
  "De la Olla",
  "Equipos Médicos Zepeda",
  "Gestiones Solidarias",
  "Sistema.bio",
  "Futuro Forestal",
  "YouGreen Cooperativa de Beneficiamento de Materiais Recicláveis",
  "Colectando Sol",
  "Zue Botanicals",
  "FC BOLA",
  "ECOPURA LIMITADA",
  "Núcleo Ambiental S.A.S.",
  "PURE CHEMISTRY S.A.S.",
  "Mejor en Bici",
  "Caja Centro",
  "Todo Accesible SC",
  "Grupo Sueñolar",
  "Grupo Secowash-SecoChile",
  "Bicicla",
  "Consultora Proa Argentina",
  "Sinba",
  "Espantapajaros",
  "R+B Diseño experimental SAS",
  "Mãe Terra",
  "Green Factory",
  "Centro del Copiado",
  "La Tercera Mirada",
  "Mamotest",
  "BAOBAB",
  "Montanya Distillers LLC",
  "Amplio Recruiting",
  "APIVITA SA",
  "purefood GmbH",
  "Permanente Dental Associates PC",
  "CajaVecina",
  "Simply Business",
  "Noonday Collection",
  "Pukka Herbs",
  "NWG Energia Società Benefit",
  "Veritas",
  "Shaw Solar",
  "Rogue Creamery",
  "The Cleaver Co.",
  "Charity Bank",
  "Northern Savings Credit Union",
  "Calsoft Systems",
  "Jia-Wei Co., CPAs",
  "Peaceful Fruits",
  "SnappCar",
  "Zoona",
  "Avante",
  "MegaFood",
  "Harvest Market",
  "Buinzoo s.a.",
  "Morton Solar, LLC",
  "FundApps",
  "VANTREO Insurance Brokerage",
  "Aspiration",
  "Atomic Object LLC",
  "Adrift Hotels SPC",
  "Pyramid Communications",
  "The TYF Group",
  "Bresco Investimentos S.A.",
  "Ipsun Power Inc",
  "Daproim Africa Limited",
  "Summerhill Pyramid Winery",
  "Articulate Marketing",
  "Hallam-ICS",
  "Heritage Aviation, Inc.",
  "SureCall Contact Centers Ltd",
  "IndiVillage Tech Solutions LLP",
  "Hopworks Urban Brewery",
  "Elephants Delicatessen",
  "Macphie Ltd",
  "Clearinghouse CDFI",
  "MPOWERD Inc",
  "Gerding Edlen",
  "WasteZero, Inc.",
  "New Chapter, Inc",
  "Immix Law Group, PC",
  "Bates Wells",
  "Amavida Coffee and Trading",
  "Positive Energy Solar",
  "Raffa, P.C.",
  "Carnegie Fabrics LLC",
  "Hilary's Eat Well",
  "Summerhill",
  "Brewery Vivant & Broad Leaf Local Beer",
  "eClass SA",
  "Constructora L y D",
  "Conexia",
  "Home Care Associates of Philadelphia, Inc.",
  "Cascade Engineering",
  "Benevity, Inc.",
  "Triodos Bank N.V.",
  "Dot Incorporation",
  "Artisan Dental, LLC",
  "Visualfy",
  "Wright Capital Gestão de Recursos Ltda.",
  "People's Architecture Office",
  "Resonance",
  "Geneva Global, Inc.",
  "Enie.nl",
  "OYORI Asia Co., Ltd.",
  "Baxendale",
  "Momenta",
  "Integral",
  "PRAGMA",
  "Russell Herder",
  "Highland Group",
  "REBBL INC",
  "Group14 Engineering",
  "Left",
  "Tweegs",
  "Antica Erboristeria SpA SB",
  "Greenline Community Ventures LLC",
  "Unreasonable Group",
  "Secure Futures, LLC",
  "Urban Mining PBC",
  "Hirepurpose",
  "CARROT Insights Inc.",
  "United Fund Advisors",
  "MullenLowe salt",
  "Imajine That, LLC",
  "Finnriver Farm and Cidery",
  "The One Brand",
  "mondora",
  "Casebook PBC",
  "North, Inc.",
  "Little Sun",
  "Grady Britton",
  "Piscataqua Savings Bank",
  "Patients Know Best",
  "Lifeblue Inc.",
  "Crystal Creek Logistics",
  "Aqua Clara Kenya",
  "Modern Adventure",
  "Asesorias Simplicity SpA",
  "Little Genius International srl SB",
  "Bettr Barista",
  "Wasafiri",
  "Abundance Investment",
  "Moonshot Academy",
  "SRI Quality System Registrar",
  "Beehive Strategic Communication",
  "Growth Mosaic Ltd.",
  "Viña Polkura SA",
  "Pekin Hardy Strauss Wealth Management",
  "Grupo GAIA",
  "ECO2LIBRIUM",
  "Grupo Educativo",
  "Way2Global Srl SB",
  "Vancity Community Investment Bank",
  "Mokulua High Performance Builder",
  "Sarape Social",
  "Banque Raiffeisen Région Genève Rhône",
  "Bloomin",
  "Pearl Capital Partners",
  "New Market Funds",
  "ShenZhen LianDi Accessibility Co.,Ltd",
  "Cafédirect PLC",
  "Tech Networks of Boston",
  "4YOU2 Idiomas",
  "Worldways Social Marketing",
  "Gelfand Partners Architects",
  "InspiraFarms",
  "MaineWorks, LLC",
  "Dean's Beans Organic Coffee Company",
  "Gary Community Investments",
  "Hawaiian Legacy Hardwoods",
  "NorthStar Asset Management, Inc.",
  "Solar States",
  "Valley City Electronic Recycling",
  "Cielo Hammocks",
  "MASECO Private Wealth",
  "Healthy Building Science",
  "Ecosia GmbH",
  "Goldstein Hall PLLC",
  "G2 Insurance Services",
  "Exponent Partners",
  "Cultiva Empresa",
  "Wendel, Rosen, Black & Dean LLP",
  "Decisely Insurance Services, LLC",
  "Enrollment Resources Inc.",
  "thinkPARALLAX",
  "Portafolio Verde",
  "Sonen Capital LLC",
  "Hybrytec Solar",
  "First Affirmative Financial Network",
  "Myplanet",
  "Estudios y Consultorías Focus",
  "Chroma Technology Corp",
  "Social Enterprises Inc.",
  "Jitasa",
  "PICnet",
  "Varsity Technologies, Inc.",
  "Turningpoint Leadership",
  "Herb Pharm",
  "Neighbourhood Group of Companies",
  "Barebones Living",
  "Facilities Management Services, Inc.",
  "Cause4",
  "Butler/Till Media Services, Inc.",
  "Paul de Ruiter Architects",
  "Funeraria del Hogar de Cristo",
  "PIXELIS",
  "Alliant International University",
  "The Big Issue Group",
  "Wetherby Asset Management",
  "Ingeus UK Ltd",
  "Aslan Brewing Company",
  "Biohabitats, Inc.",
  "Thanksgiving Coffee Co.",
  "tentree international",
  "Royal Van Wijhe Verf B.V.",
  "BioCarbon Partners",
  "PEGAfrica",
  "Beyond English",
  "WildHearts Group",
  "Crosby Hop Farm, LLC",
  "PenFinancial Credit Union Limited",
  "TruTrade Africa",
  "REAL Fundraising",
  "Vistage S.A. Argentina",
  "Global Prairie",
  "Dinâmica Soluções Ambientais Ltda",
  "norsys",
  "Specialisterne Spain",
  "Órigo Energia",
  "Lombard Odier",
  "Grameen Danone Foods Ltd",
  "Living Room Realty",
  "Baldwin&",
  "Oliver Russell & Associates",
  "Cloud for Good",
  "Greentech Capital Advisors",
  "Breckinridge Capital Advisors, Inc.",
  "EcoZoom",
  "Virginia Community Capital",
  "Gray Ghost Management & Operations LLC dba Gray Ghost Ventures",
  "B-Line Urban Delivery",
  "Responsible Leadership Foundation t/a The Forward Institute",
  "Insieme Società Cooperativa Benefit",
  "Helsinki Capital Partners",
  "Faro Energy",
  "Cricket Design Works, Inc.",
  "Pringle Creek Community- Sustainable Investments",
  "Glatt Stove",
  "West Arete",
  "The Soulfull Project, PBC",
  "Sierra Leadership LLC",
  "ekodev",
  "Upohar LLC",
  "Stroopies, Inc.",
  "Synergy Enterprises",
  "SQUIZ",
  "Shades of Green Permaculture",
  "MediaStyle Inc",
  "ReGrained",
  "Troon Pacific, Inc.",
  "Winderlea Vineyard and Winery",
  "Angel Oak Creative",
  "Greenvines",
  "BIRDEO",
  "Impact Partner GmbH",
  "Fair Game Beverage Company",
  "GreenSpark Energy",
  "Brewgooder",
  "Baluarte Cultura",
  "Catalyst Partners",
  "Oficina da Sustentabilidade",
  "Alcagüete",
  "STC Sunbelt SpA",
  "Colorado Impact Fund",
  "Wired Flare Inc.",
  "Hora Salud",
  "Impact Hub Oakland",
  "Wider Sense GmbH (previously Beyond Philanthropy invest impact GmbH)",
  "C and L LLC dba Conscious Coffees",
  "Vava Coffee Ltd.",
  "Pley School Internation .Co",
  "Delphis Eco",
  "the bread and butter",
  "21gramos",
  "MySezame",
  "Spazio Noprofit s.r.l. Società Benefit",
  "Soapbox",
  "Earth Equity Advisors",
  "Wilkinson Mazzeo PC",
  "Jasberry Co., Ltd.",
  "Community Purchasing Alliance",
  "Tella",
  "Zip Code East Bay, Inc.",
  "Babo Botanicals",
  "Tawil Comunicação",
  "One Nature LLC",
  "Carbon Gold Ltd",
  "Optimize Enterprises, PBC",
  "Moyee Coffee",
  "Mujeres del Pacífico",
  "Realize Strategies",
  "Insurance Masters NW",
  "Get Help",
  "Mortgage360",
  "Once Upon a Farm LLC",
  "D-Orbit",
  "Global Gaming Initiative",
  "Strauss Energy Ltd.",
  "PHLUR",
  "Impact Benefits & Retirement",
  "ARU",
  "LimeRed",
  "JUMP Consulting Limited",
  "Jelt",
  "Insource Renewables",
  "Grupo Contempo S.A.S",
  "Ash Creek Forest Management, LLC",
  "Major League Hacking (MLH)",
  "Fluid IT",
  "ClimateCare",
  "Well Clinic",
  "The Hub Kings Cross Ltd",
  "Plongê",
  "Waste Farmers",
  "Turnstile Tours",
  "Lucky Iron Fish Enterprise",
  "Foncière Chenelet",
  "SINGULARES",
  "SITAWI",
  "Plastic Whale",
  "InVento Innovation Lab impresa sociale srl",
  "New Resource Solutions, LLC",
  "Grey Rock Clothing Co.",
  "Grassroots Capital Management Corp PBC",
  "Lotus Foods",
  "3Sisters Sustainable Management, LLC",
  "Preserve",
  "Larry's Coffee",
  "Clean Yield Asset Management",
  "Recyclebank",
  "Brightworks Sustainability LLC",
  "Alter Eco",
  "Partnership Capital Growth",
  "Co-op Power / Northeast Biodiesel",
  "Joule, LLC",
  "Recicladora Urbana",
  "Criando Consultoria",
  "NAVA Real Estate Development",
  "Soleventus",
  "Packaging 2.0, Inc",
  "MRW Connected, Inc.",
  "Republik",
  "Natural Organic Process Enterprises",
  "Simply Straws",
  "Urbane & Gallant",
  "CRIDEM",
  "Fingerlakes Wealth Management",
  "Radicle Impact Partners",
  "Singlebrook Technology",
  "Animal Experience International",
  "Yellow Leaf Hammocks",
  "Barrett and Welsh",
  "CoMetrics",
  "Volans",
  "Ovis 21",
  "Senda Athletics",
  "Dimensions in Occupational Health and Safety",
  "Good.Must.Grow. LLC",
  "Law Office Of Lara Pearson & Brand Geek",
  "Urban Green Development, LLC",
  "Richmond Grid",
  "evolveEA",
  "Feronia Forests LLC",
  "Better Way Designs",
  "Cage Free Productions",
  "Ogunte",
  "Griswold and Griswold Insurance Agency",
  "Recollective Consulting",
  "7group, LLC",
  "The Restorative Leadership Institute",
  "Thinkshift Communications",
  "Rivanna Natural Designs, Inc.",
  "Core Capital Management",
  "SVT Group",
  "Adam Shay CPA, PLLC",
  "CSRHub LLC",
  "CR-Building Performance Specialists",
  "Rain Water Solutions, Inc",
  "Ditto Hangers",
  "Andy Smith Photography",
  "Saul Good Gift Co",
  "Canvas Host",
  "Unity Digital Agency",
  "Holaluz",
  "Participate Learning",
  "Change.org",
  "thedatabank, Gbc. (General Benefit Corporation)",
  "Plum Organics",
  "Generation Investment Management LLP",
  "Veris Wealth Partners",
  "Untours",
  "Trillium Asset Management",
  "IceStone",
  "Greyston Bakery, Inc.",
  "Back to the Roots, Inc.",
  "Solberg Manufacturing, Inc.",
  "Terra Education, Inc.",
  "Peace Coffee",
  "HEX Ferments",
  "Increase",
  "LifeCo UnLtd Investments",
  "Finhabits",
  "BAU Accesibilidad",
  "Capital Plus Financial, LLC",
  "Closed Loop Partners",
  "Cuestamoras Bosques",
  "Suindara Radar e Rede",
  "Effective Assets, Inc.",
  "CSMlearn",
  "Kit Urbano",
  "Taurus Capital SAS",
  "Black Fox Philanthropy LLC",
  "U.B.Q MATERIALS LTD",
  "Tribe Impact Capital LLP",
  "Beta Bionics, Inc.",
  "Rumi Spice, PBC",
  "WHEB Asset Management LLP",
  "Investir&+",
  "Limited Resource Teacher Training",
  "Public - Supply",
  "Lendahand",
  "Unforgettable",
  "Benefacto",
  "greenApes",
  "New Citizenship Project",
  "2B Community",
  "Higher Grounds Trading Company",
  "Just Coffee Cooperative",
  "Sudara Inc.",
  "Goldfarb Financial",
  "Above Green LLC",
  "Prichard Communications, Inc.",
  "Worldcoo",
  "CleanNow",
  "Persephone Brewing Company",
  "ENGIE Rassembleurs d'Énergies",
  "CNote Group, Inc.",
  "Pathway21",
  "Sea to Sky Removal",
  "Riverwater Partners",
  "10Power",
  "Farmidable",
  "Kuza Biashara Limited",
  "Newday Impact Investing",
  "Openly",
  "Mission Driven Finance",
  "Santa Francesca Cabrini srl - Società Benefit",
  "Imagin/able",
  "GenerationHope, Inc.",
  "HoneyBee",
  "FindShadow, PBC",
  "3x5 Partners",
  "Mandala Naturals",
  "JBA Wealth Management Group",
  "Laia’s Proteinhanf GmbH",
  "Davis Benefits & Pensions Ltd.",
  "ARS s.r.l.",
  "Wholegrain Digital",
  "Kotmo",
  "Sons & Daughters, Inc",
  "Good Planet Innovation",
  "Bainbridge Vineyards, LLC",
  "Revenue Automation Inc",
  "Montanaro Asset Management",
  "Big Mamma",
  "Sarona Asset Management Inc",
  "eKutir",
  "Equilibrium",
  "Give Something Back Workplace Solutions",
  "Ingage Partners",
  "Iroquois Valley Farmland REIT",
  "The Tea Spot PBC",
  "LUMNI CHILE",
  "Pegas con Sentido",
  "BluPlanet Recycling Inc.",
  "PlanoCDE",
  "Enviro-Stewards",
  "Sustainable Harvest",
  "RSF Capital Management PBC",
  "Renewal Funds",
  "fitppl",
  "Welight",
  "Frogsong Farm, LLC",
  "atlasGO",
  "Terra Genesis International, LLC",
  "Ossa Organic",
  "Rockridge Venture Law",
  "MADE OF",
  "Semantrica Ltd",
  "MapleMama Beverages LLC",
  "ABURY Collection",
  "Palto",
  "Merge4 Mfg, Inc",
  "GEA",
  "Reborn B Corp",
  "Megan A. James Photography",
  "Wanderwell",
  "Carnes Naturales SpA",
  "Pause i/O",
  "Etho Capital, LLC",
  "Blue Ocean Office Supplies & Solutions",
  "WashPark Capital",
  "Odyssey Labs LTD",
  "Keene Advisors, Inc.",
  "The Alinker Inventions Ltd",
  "Clear Blue Commercial",
  "Dibago",
  "Brasserie NewDeal Brewing Co.",
  "Boomerang Information Services, Inc.",
  "MANRESANA de MICOBACTERIOLOGIA, S.L",
  "Green Commuter",
  "Lulea Mindful Athletes S.A.",
  "EPOCH PI",
  "Scrumbles",
  "Stay True Clothing",
  "Northeast Green Building Consulting, LLC",
  "Atticus",
  "Selletiva",
  "Door94, Inc.",
  "Palm Key",
  "The TAN2000 International Regulatory Corporation",
  "Tuckerman & Co.",
  "Marigold Capital",
  "Newly, Inc.",
  "Yala Jewellery",
  "Meliora Cleaning Products",
  "Arueira Ambiental",
  "Give-a-Seat",
  "Neighborhood Sun",
  "TripZero",
  "Thread Talk",
  "Sense-Lab",
  "Creative Action Network",
  "SALOMMON IDEAS EN ACCIÓN",
  "Conscience Bay Company LLC",
  "REMBRE",
  "ZYN",
  "Rising Sun Chile",
  "EcoAdvisors",
  "adhara organic",
  "Chris Bertish - IMpossible",
  "Jason Wiener, P.C.",
  "Kung Fu Accounting",
  "PowerDash Inc.",
  "LORF S.B. SRL",
  "Y8 studio, Inc.",
  "Helping Habit PBC",
  "UpDIG",
  "Allied Cloud",
  "Wisdom Supply Co.",
  "Rescue Chocolate",
  "Social Impact Architects",
  "ArcTern Ventures",
  "tbd*",
  "Metis Consulting Group",
  "Wekiwi Srl",
  "Blue Beautifly LLC",
  "Norlha",
  "Aguas Santa Amalia S.A.",
  "Courrieros",
  "Best Energy",
  "The Green Engineer, Inc.",
  "Yulu Public Relations Inc.",
  "Broota SPA",
  "Link2Feed Inc",
  "New Society Publishers",
  "Sustrana LLC",
  "TMI Consulting",
  "Impakt",
  "Needo",
  "Kinvolved",
  "Wildwood Ecology Limited",
  "Alter Ego",
  "Pitaya Plus",
  "Lineage Botanica",
  "Urban Foundry Ltd.",
  "Bliss Healthcare Services, INC",
  "Naked Ideas Limited",
  "The Beeswax Wrap Company Ltd",
  "Facile Aiuto",
  "WeNow",
  "SkyFire Energy Inc",
  "Town Square Spaces Ltd.",
  "Seetec",
  "Inesscents Aromatic Botanicals",
  "Ethical Profit Accounting Agency",
  "Manitoba Harvest Hemp Foods",
  "Keen Bull",
  "Relish New Brand Experience Inc.",
  "Walden Hyde",
  "Phil Communications",
  "Cafe Belong",
  "She Geeks Out, LLC",
  "Sun & Swell Foods",
  "Assomption Vie",
  "Signature Breads",
  "The Sox Box",
  "Imperative",
  "American College of Education",
  "Catalyst Law, LLC",
  "Keela (by Networks for Change)",
  "T-Global Technology",
  "Shift Workspaces",
  "Rice Fergus Miller",
  "dmarcian",
  "Beekeeper's Naturals Inc.",
  "GIVN Goods",
  "Classcraft",
  "BRIGHTNESS SAS",
  "Better Bean Company",
  "Beartooth Group",
  "Havas London",
  "C-Level",
  "Vivejar",
  "Spring Activator Inc.",
  "Beauty Kitchen UK Ltd",
  "Ming Yung Enterprise Co.,Ltd",
  "Prospectus",
  "Oneplanetcrowd",
  "EXE.IT Srl Sb",
  "Le Rêve du Dogon",
  "PUR Projet",
  "Qbic Hotels",
  "microDON",
  "Respect Group",
  "Career Aviators",
  "Birus",
  "Organic Bliss, Inc.",
  "MEJDI Tours",
  "Raiffeisen Servizi Assicurativi Srl",
  "148",
  "SIDIESE",
  "GreenSpot Global",
  "WA Verlichting B.V.",
  "Ulule",
  "Instinctus Co., Ltd.",
  "Peace Power",
  "Ocean First, LLC",
  "Turn-Key Marketing & Promotions, Inc.",
  "Fido Systems",
  "Sustainable Insight Capital Management",
  "Bagito",
  "Just Move In",
  "Misteli Creative Agency",
  "S. Sunshine & Associates",
  "Ecotrend Ecologics Ltd.",
  "L&Co Design Ltd.",
  "One Better Ventures II, LLC",
  "Conscious Company Media",
  "SkyHive Technologies Inc.",
  "Selfless.ly",
  "hudi",
  "Teadora",
  "Mindful Chef",
  "Shift Capital",
  "Lafes",
  "GrantBook",
  "Optimist",
  "OluKai",
  "LEAP Organics",
  "Pie Pan, Inc. DBA Bull City Burger and Brewery & Pompieri Pizza",
  "Urbanspace Property Group",
  "GI Quo Vadis Inc",
  "U Konserve",
  "Whole Kids",
  "TCC Group",
  "The Joinery",
  "LineSync Architecture",
  "Mikado Consulting",
  "FlipGive",
  "Human Investing",
  "Finisterre",
  "Protopia",
  "Brew Tea Company",
  "Synthesis Life Insurance",
  "Jenny Kassan Consulting",
  "HELPSY",
  "Bulb",
  "Sagent",
  "bambu",
  "NEWMANITY",
  "igloo Regeneration Ltd",
  "Genexa, Inc",
  "Futerra",
  "On The Rocks",
  "Obvious Ventures",
  "Klean Kanteen",
  "Eco-Products, Inc.",
  "Mulanje Tea Imports",
  "HiTECH Assets, LLC",
  "Dunlap Law PLC",
  "Merritt & Merritt",
  "Eco Promotional Products, Inc.",
  "All Things Open",
  "DANONE AQUA Indonesia",
  "Smiile",
  "Green Energy Options of Keene",
  "Pixellu",
  "Mamava, Inc.",
  "reThink llc",
  "Neighbourly",
  "Orientea Enterprise Co., LTD.",
  "The Social Investment Consultancy",
  "Dermophisiologique Srl SB",
  "Wessanen UK (trading as Kallo Foods Ltd)",
  "Scale Up SCRL",
  "beebox",
  "PHENIX",
  "Captain Blankenship",
  "Symditravel Service",
  "TENZING",
  "Savy",
  "Wellspring Consulting LLC",
  "Evident (www.itsevident.com)",
  "M Creative",
  "Artattack Group S.r.l.",
  "LETZ SUSHI",
  "KLG Fine Food Company Limited",
  "Tenfold Health",
  "Canidé",
  "Being Development",
  "Be Inspired Films",
  "Frank Bold",
  "Kregel & Company CPA",
  "Bungaloom",
  "Brinkman",
  "Beryl",
  "Impact Hub Taipei",
  "Ad Victoriam Solutions",
  "Scout Books",
  "Modern Species",
  "Green Drop Garage",
  "Yoti",
  "Lyda Law Firm LLC",
  "Bethnal Green Ventures",
  "Co-School SAS",
  "Natural Development, Inc.",
  "Echo Adventure Cooperative, Inc",
  "Branching Minds, Inc.",
  "Visceral",
  "Mayra Alimentação Infantil",
  "Prosper Strategies",
  "GROSCHE International Inc.",
  "Adams Green Consulting Limited",
  "Archer Investment Management",
  "Sloco Massage + Wellness Spa",
  "The Refill Shoppe",
  "Domoto Brands",
  "bigtruck®",
  "Business Performance Improvement",
  "Civil Support Public Benefit Ltd.",
  "Taiwan Dive Center",
  "Más Verde",
  "Avenue",
  "Raízes Desenvolvimento Sustentável",
  "s.e.e.d.",
  "Selecta Auto Body",
  "Boardwalk Capital Management",
  "Acción Verde SAS",
  "Luscious Garage",
  "PWPvideo",
  "SKINourishment, Inc.",
  "SMART COACH SPA",
  "Casa Collab Global S.A.C",
  "Yoroom",
  "Karsharing SPA",
  "French Broad Chocolates",
  "Unboxed, S.C.",
  "AMAGI Desarrollo Humano",
  "Cupanion",
  "ImpactReady",
  "ECOALF RECYCLED FABRICS, SL",
  "Pecsa",
  "Plaine Products",
  "B GIFT SPA",
  "The Raw Office",
  "Microfranquicias con Impacto Social",
  "Vivid Story",
  "Extend Comunicaciones",
  "Food.Stories.Travel.",
  "Kulshan Services LLC",
  "Sunshine Coast Health Centre (2005) Ltd.",
  "Apiary Studio LLC",
  "Treefort Music Fest",
  "Current Shift",
  "Team Tipton (R S Tipton, PBC)",
  "Public Inc.",
  "Yogini, LLC the zen of slow cooking",
  "Sustainable Pacific Consulting",
  "Red-Inc",
  "Cornucopia Natural Foods",
  "Brew Dr. Kombucha",
  "Humankind Research",
  "PROPERCORN",
  "Vermont Creamery",
  "Novex Delivery Solutions",
  "Andean Naturals, Inc.",
  "Greenerprinter",
  "EcoLogic Solutions Inc.",
  "Environmental & Public Health Consulting",
  "Kaffe Bueno ApS",
  "D'orica Srl Società Benefit",
  "De Smaakspecialist",
  "Ecosphere+",
  "LeDaveed",
  "Slow Food Promozione S.r.l. S.B.",
  "goodDog",
  "TGW Studio (This Good World Network, LLC)",
  "Ecolution Consulting",
  "Vital Plan",
  "Trustees Unlimited LLP",
  "TeroLab Surface GmbH",
  "On Purpose",
  "De Krat",
  "CONSERVAS ANTONIO PÉREZ LAFUENTE, S.A.",
  "1000friends & La Casa de Carlota",
  "Baleco",
  "Ecoflora Agro S.A.S",
  "Heincke SAS",
  "EcoInnovate",
  "Hog Island Oyster Co. Inc",
  "Cotswold Fayre Ltd",
  "Gemma",
  "Old Structures Engineering",
  "Clean the World Global",
  "SAGE Sustainability",
  "DAME.",
  "Pyrrha",
  "Invivo Clinical",
  "Cabinet d'avocats NOVAlex Inc.",
  "Carla Fernández | Comercializadora de Diseño Flora SAPI de CV",
  "Aprendizaje Inteligente",
  "Twine Fair Trade Company",
  "Just Ask Estate Services Limited",
  "Threespot",
  "OnSite Energy, Inc.",
  "Redeleit und Junker GmbH",
  "Ecotone Analytics GBC",
  "theturnlab inc.",
  "Solidarity Capital Group",
  "Fishpeople",
  "Real Leaders",
  "The Change Creation, Inc.",
  "Hanson Bridgett LLP",
  "Dogeared",
  "Healthy Buildings International Inc.",
  "Catchafire",
  "Atchley & Associates, LLP",
  "Money Positive",
  "Greenprint Partners",
  "Propeller Coffee Co",
  "Vert Asset Management",
  "Arcadia Technology, Inc.",
  "VPL",
  "ONE CREATION Cooperative",
  "Blazin' Babes",
  "The Trust Partnership",
  "Swift Printing & Communications, Inc.",
  "Beam Consulting",
  "Toto Pet Insurance",
  "Makes Scents Natural Spa Line | Hempfield Botanicals",
  "Social Network Co., LTD ( NPO Channel、 1 for one )",
  "Goddess Garden",
  "The GFB",
  "La Ciudad Posible SRL",
  "The Image Shoppe",
  "Inclusio",
  "Smart Air",
  "Waterleaf Architecture",
  "Ginger Salon Inc",
  "Gridworks",
  "ADEAS Hr",
  "Warm Springs Consulting LLC",
  "Libélula Gestión en  Cambio Climático y Comunicación",
  "Tribe 9 Foods",
  "DA.AI Technology",
  "Werkliv",
  "The Terrace BV",
  "Alaska Glacial Mud Co.",
  "The Black Sheep Agency",
  "Hawaiian Paddle Sports, LLC",
  "Bond&Devick Wealth Partners",
  "Green Glass",
  "Therafit Shoe",
  "Charter School Business Management-FOREsight",
  "OpenConcept Consulting Inc.",
  "Country Life LLC",
  "Impact Hub Seattle",
  "Seeds Printing",
  "Bhakti Chai",
  "Matter Unlimited",
  "Communitas Financial Planning",
  "Oaklandish",
  "Dolphin Blue, Inc.",
  "United By Blue",
  "bCause",
  "Fireclay Tile",
  "Homefree",
  "Erbaviva",
  "Modernist Financial, LLC",
  "Futurekind",
  "Vegetarian Express Ltd",
  "Mimetics Inc.",
  "WhyWhisper Collective",
  "Radish Lab",
  "Managing A Sustainable Business, S.L.",
  "Ox Verte",
  "Sentido Verde",
  "Mialuna",
  "Genética del Este S.A.",
  "Bowlpark",
  "NOOMA",
  "Noticias Positivas",
  "Hemper Handmade",
  "Centro de Liderazgo Adaptativo",
  "Productos Naturales Aral Thel S.A.",
  "Dang Foods LLC",
  "Encircled",
  "Teatulia Organic Teas",
  "Tree Planet",
  "Headwater Food Hub",
  "Vault + Vine",
  "DVIGI",
  "NetRaising",
  "Travolution",
  "BlueDot",
  "rTraction Canada, Inc.",
  "Herbalist & Alchemist",
  "Where There Be Dragons",
  "Felidarity",
  "Marealis AS",
  "Winnow",
  "Greyfos",
  "Subtext",
  "SYSTEMIQ Ltd",
  "Boboto s.r.l.",
  "FREY Brothers, LLC",
  "Bubble Chamber CIC",
  "Planet Bluegrass",
  "Boloco",
  "Cape Venture Wine Co.",
  "Prosperity Candle",
  "Mamma Chia",
  "Akamai",
  "SVX México",
  "GITEC BRASIL",
  "MIELES S.A.S.",
  "INBONIS s.a.",
  "Social Docs",
  "J.Kraft Group AB",
  "All Set Comunicação",
  "Zen for Business",
  "5 Lakes Energy",
  "Positiva Holding Ltda",
  "ClearSale",
  "Positive Ventures",
  "VEJA",
  "Uncommon Cacao",
  "Fazenda Da Toca Orgânicos",
  "MOVIN",
  "Upward Technology",
  "TecVolt",
  "Aniyami",
  "E-Waste Solutions",
  "Tofurky",
  "keiff kefir ltda",
  "PALO IT Singapore",
  "AgroTools",
  "AE Works",
  "Oster Design",
  "Insolar Assessoria Empresarial e Social Ltda.",
  "Brilia (razão social Swell Imp./Com. de Produtos de Iluminação SA)",
  "Ossorio Domecq/Maison Domecq",
  "Rise Ventures",
  "Synergy Clothing Inc",
  "Callaly",
  "Oxygen House",
  "Orbis Environmental",
  "Aoka",
  "Falcon Waterfree Technologies",
  "Moye White",
  "EdOps",
  "WE Family Offices LLC",
  "UrbanVolt",
  "Brink Communications",
  "Hotel Ease ‧ Tsuen Wan",
  "Real Oyster Cult",
  "B1G1",
  "Nissan Tsushin Co. Ltd.",
  "NextEdge Networks Holdings, LLC & Modus, LLC",
  "Haint Blue Brewing Company",
  "Jahmu PBC",
  "Soma",
  "QoC Health",
  "EcoMatcher Limited",
  "Vision Strategy Storytelling Pte Ltd (VSStory)",
  "Flipside Creative",
  "Ventegra",
  "Wasmer, Schroeder & Company",
  "PlusUs",
  "Tree-Mendous Aerial Adventures",
  "Telesis Corporation",
  "Taitem Engineering, PC",
  "Impact First Investments",
  "TriLinc Global",
  "Broterra",
  "Copernicus Educational Products",
  "Winkler Partners",
  "Squeaky",
  "Codalis SA",
  "Flooglebinder",
  "WEN TANG TEA CO., LTD",
  "Good Cloth, LLC",
  "TODO1 COLOMBIA LTDA",
  "OTEC El Circo del Mundo",
  "OTA Franchise Corporation",
  "FARAD Group",
  "Freeformers",
  "Ethikos 3.0",
  "LIM Cosmetics GmbH",
  "CAMIF MATELSOM",
  "BBK/Door Vriendschap Sterker",
  "Ecojun Company",
  "La Ruche qui dit Oui !",
  "Luxelare",
  "The Morne Wine Company dba Brooks Wines",
  "Gustavo Trading GmbH & Co. KG",
  "Light Trail Consulting",
  "Qero Ecovasos",
  "SMAK Food Inc",
  "DISRUPTIVO",
  "Lacteos y turismo Playa Venado",
  "Ralí SpA",
  "Riverside Natural Foods Ltd.",
  "Brand Solutions Ltda",
  "Karün",
  "LeadDog Marketing Group Inc.",
  "Purely Elizabeth",
  "The Bulb",
  "Yever",
  "MuLondon",
  "Ishii Zouen Landscape Co., Ltd.",
  "Navitas Organics",
  "TallGrass",
  "Aero Studiodesign",
  "Centor Insurance and Risk Management Ltd",
  "goodforgrowth GmbH",
  "Forrest Firm, PC",
  "Tonka SA",
  "TcUrbes",
  "Coda Coffee",
  "Acorn Sign Graphics",
  "Orbit Media Studios, Inc.",
  "INTI ZEN",
  "Aquatic Informatics",
  "Galileo Learning",
  "Farmland LP",
  "Waterbomb Ltd",
  "Vert & Vogue",
  "ResolvJa Aplicativos Especializados Ltda.",
  "KSV",
  "Scratch and Peck Feeds",
  "Solarus Sunpower",
  "Oplus",
  "BioRumo",
  "Actitudlab",
  "CAUSE",
  "PUCCI",
  "New Leaf Community Markets",
  "R+M Agency",
  "Corporate Knights",
  "Mission Hub LLC",
  "Intex Solutions, Inc.",
  "Savvy Rest, Inc.",
  "EartH2O",
  "Tiffinday Inc.",
  "Kickstarter PBC",
  "Fair Trade Jewellery Co.",
  "EO Products",
  "Blue Star Integrative Studio",
  "Kruz, Toca Madera",
  "Chia Pang Plastics Co., Ltd.",
  "Pharos Systems International",
  "Only Natural Pet",
  "Natural Force Benefit Co.",
  "Farmacie Fiorentine AFAM SpA SB",
  "Public Democracy, Inc.",
  "Mission Partners",
  "MIGHTY ALLY",
  "Truefaux Films Inc",
  "ClearlySo Limited",
  "Native Trails, Inc.",
  "NuttZo",
  "Wallaroo Hat Company",
  "SinnovaTek",
  "allplants",
  "MiiR",
  "KAMMOK",
  "Found My Animal",
  "Sea to Table",
  "Good Clean Love",
  "GladRags",
  "Equator Coffees",
  "Ethical Markets Media, LLC",
  "Context Travel",
  "Stash Tea",
  "Capricorn Investment Group, LLC",
  "Blue Hill Partners LLC",
  "Naturescapes",
  "nextOPP Search",
  "Mark Leibowitz Photography Inc.",
  "New Outlook Financial, LLC",
  "Sustainable Restaurant Group",
  "GroundFloor Media",
  "Upslope Brewing Company",
  "Veritable Vegetable",
  "Tangiers International",
  "Integra Chile S.A.",
  "Cervecera Guayacan SpA",
  "GOODONYA® Cafe",
  "Eminence Organic Skin Care Inc.",
  "Nisolo",
  "Good Food",
  "Good & Well",
  "Gung Ho! Pizza",
  "One Hundred Seconds",
  "Teterum SL",
  "Seats2meet.com",
  "Sugi Group AB",
  "Arbos Srl",
  "Sencha Naturals",
  "WASTE IS MORE (CLIP IT)",
  "Quorum",
  "Good Stuff Partners",
  "Sustainable Business Partners",
  "Ondulé",
  "Emprendia",
  "Baabuk Sàrl",
  "Next Door Photos",
  "The Good",
  "CAUSEBOX",
  "Nia Impact Advisors, LLC",
  "Capital Factory",
  "Ocean Sonics",
  "Murphy's Naturals, Inc",
  "Technicians For Sustainability",
  "True Impact",
  "Colorado Capital Management",
  "S.W. Basics",
  "TS Designs, Inc.",
  "SABEResPODER",
  "Comet Skateboards",
  "Better World Books",
  "BBMG",
  "JSA Financial Group",
  "Blédina",
  "SPUD.ca",
  "Accompany",
  "Allos Hof-Manufaktur",
  "Dopper B.V.",
  "Imery & Co, LLC",
  "Yuxta",
  "Whole Whale",
  "Wehl Inc.",
  "The Clarius Group",
  "School for Startups",
  "Observer Media Group",
  "Climate Neutral Group",
  "Unbelts",
  "Ando Reciclaje",
  "Loyco",
  "Vox Pop Labs",
  "Pearl Street Communications Inc",
  "Opaline SA",
  "Azavea",
  "Apolis Holdings LLC",
  "BeBright",
  "Schuttelaar & Partners",
  "Nudge B.V.",
  "Wild Friends Foods",
  "vacavaliente",
  "Deltec Homes, Inc.",
  "White & Elm",
  "Alexis Advisors",
  "Infopan SRL",
  "Longview Asset Management LLC",
  "Marmoset",
  "Drive Change Foods LLC",
  "Sword & Plough",
  "Evrnu, SPC",
  "Verco Advisory Services Limited",
  "GMF Latinoamericana SA",
  "Green4Good - Compugen Finance",
  "Boomera",
  "AZ QUEST",
  "SICLO RURAL",
  "Soko Inc.",
  "Ecofactory",
  "Finsocial sas",
  "Sustainable Societies Consulting Group",
  "Reos Partners",
  "Nómades - Yachay Lab S.A.C",
  "Omnifarious Ltd. - Omni Productions & Omni Digital",
  "Grameen de la Frontera",
  "Haus des Stiftens gGmbH",
  "Creative Energies",
  "CONINCO Explorers in finance",
  "Longview Structures LLC",
  "OTAVIANO BODEGA & VIÑEDOS",
  "Urbani Limitada",
  "Gladstone Hotel (Toronto) Limited",
  "Manifesto",
  "PATAGUA",
  "Jardin Infantil Arándano",
  "BirdsChile",
  "Gestión Humor ltda",
  "Moddo Marketing Lab",
  "Spiral Criativa",
  "Highlander",
  "ABISSAL Capitalismo Saudável",
  "Amazonas Explorer",
  "EPONYME",
  "Absolute Pilates",
  "Entrust Financial",
  "EarthHero",
  "Environmental Incentives, LLC",
  "ORIENS GESTIÓN CULTURAL",
  "CANVAS Estrategias Sostenibles",
  "MOR Wealth Management, LLC.",
  "Mais Fácil Instituição de Pagamentos S/A",
  "Alvéole",
  "Impact Hub Bern",
  "Tobasa Bioindustrial de Babaçu S/A",
  "Investisseurs et Partenaires",
  "Yunus Negócios Sociais Brasil",
  "Grupo Florex",
  "RECYCART SRL",
  "EdComs Ltd",
  "Dialogue Experience",
  "De Lolita Restó Café",
  "Cooperativa Magis",
  "Kodama y Mex",
  "Donadora",
  "Pixza",
  "Skagerak Denmark A/S",
  "Rubber Republic",
  "eduK",
  "Sufferfest Beer Company",
  "Greenhouse PR",
  "Programa Vivenda",
  "Palmetto",
  "Farm Brothers",
  "AccertaClaim Servicorp Inc.",
  "Do Some Good",
  "Luz Libre S.R.L.",
  "BO Berlin Organics GmbH",
  "Nuova Vista",
  "Sol Organica",
  "MobileServe",
  "Reconectta",
  "Camping",
  "Companhia Melhoramentos de Caldas Novas - LAGOA QUENTE",
  "Scream Agency",
  "TOOVALU",
  "Investing for Good",
  "NBTA Credit Union",
  "Mackey Advisors",
  "Eltoro Studio",
  "Energage",
  "Doisy & Dam Limited",
  "Impact Marathon Series",
  "AGLH/ Estancia Las Quinas",
  "Dr. Brite",
  "Coopérative Mu",
  "Wirefire",
  "CPI Risk, Finance & Governance",
  "NEXOOS GROUP S.A.",
  "North Coast Organics LLC",
  "Resource Futures",
  "Starters4Communities",
  "SANDSTONE Asset Management Inc",
  "Greenbanc",
  "RET",
  "LA 25 SPORT",
  "EM Projectes Didactics",
  "SunBug Solar LLC",
  "Lohas Beans",
  "Geekie",
  "Eastern Carolina Organics",
  "MUD Jeans International",
  "DeeBee's Organics",
  "Vital Choice",
  "BancoEstado Microempresas",
  "Raining Rose Inc.",
  "wehlers",
  "MediaResponsable S.L.",
  "New Hope Ecotech",
  "MAGIKJC EMPREENDIMENTOS IMOBILIÁRIOS",
  "HAATCH (formerly AK2C)",
  "Metrio",
  "Society",
  "Fresh Prep Foods Inc.",
  "Rise",
  "Espacio Arroelo Coworking SL",
  "PEEKABOO ORGANICS, LLC",
  "Denda",
  "Physicians Thrive",
  "SAY",
  "Green&Blue",
  "Good Innovation",
  "We Are Tea",
  "Patrus Transportes Urgentes Ltda",
  "Kimso",
  "Cambará Eco Hotel",
  "LAGARDE S.A.",
  "Abel & Cole",
  "Sanar",
  "Uop! (Savia Vida SpA)",
  "Olympia Coffee",
  "Casa Fen",
  "Parker Clay",
  "HiMama Inc",
  "Negocios Sociales Mexico, SAPI",
  "filóo vale sua saúde",
  "CAFEXPORT",
  "Alpro (Alpro SCA)",
  "PENSIUM, SL",
  "TACK10 Strategy",
  "Rosario Bio Energy",
  "Valorar Futuro",
  "Promosumma",
  "Books S.R.L.",
  "Terrasos SAS",
  "Mymag editora",
  "SuperFoods Ecuador",
  "Empresa Social Recidar S.A.C.",
  "APPA Real Estate",
  "casa feito brasil",
  "Baisikeli ApS",
  "Confluence Sustainability",
  "Stroud Brewery",
  "Flow Water Inc.",
  "Stevia del Condado",
  "Laboratoires Expanscience",
  "JUST Goods, Inc.",
  "C.V.L.T coop.agr Zanolari",
  "Treedom",
  "Surplus Service",
  "Northeast Solar Design Associates",
  "Pour le Monde Parfums",
  "Jelly Digital Marketing & PR",
  "Anoche tuve un sueño Global Magazine",
  "SUSTAINABLE ISLAND PRODUCTS",
  "And Rising",
  "Dictuc S.A",
  "Snowflake, LLC",
  "Careershifters",
  "Impact and Growth Advisors",
  "The Alchemist",
  "Mustard Seed",
  "Kaeté Investimentos",
  "campus b",
  "Peixes da Amazônia S.A.",
  "Mama Earth Organics",
  "Easthall Farm at St Pauls Walden",
  "recyclivre.com",
  "Do Nation",
  "Escape the City",
  "The Revelry Group",
  "Werba S.A.",
  "soulproducts GmbH",
  "Vertical",
  "Cloud City",
  "grün versichert GmbH",
  "Citizen Capital",
  "SUSTREND Spa.",
  "Accès Personnel SA",
  "DES ENJEUX ET DES HOMMES",
  "Startnext Crowdfunding GmbH",
  "The Manipedi",
  "ARP-Astrance",
  "Caribbean Civil Group Ltd.",
  "Globalance Bank",
  "HEX",
  "Softweb",
  "Elvis & Kresse",
  "Indi.us",
  "SlantShack Jerky",
  "Araruna Filmes",
  "Social Value UK",
  "Retalhar",
  "Alfa Accountants en Adviseurs",
  "Suministros Analogico Digitales, S. de R.L.",
  "Nature Services Peru",
  "Work Wisdom LLC",
  "Rhiza Capital Inc.",
  "SunFresh Produce Limited",
  "MobSquad",
  "Kennedy Woods Architecture",
  "IguanaFix LTD",
  "BetterGreen",
  "Les Grappes",
  "Fluid Branding",
  "Insurance for All(IFA) Insurance Agency Ltd.",
  "Solutions Will",
  "Let's Create Africa",
  "Poppy Barley",
  "Cole Valley Partners",
  "Beyond Green",
  "Benefect Corp",
  "Made with Local Snack Foods Inc",
  "The Heritage Bee Co.",
  "miEnergy",
  "Legacy Vacation Resorts",
  "Laridae Communications Inc.",
  "Nada",
  "Fondify",
  "FLOR DE DOÑANA",
  "Dialogue",
  "IG4 Capital",
  "Braibook,SL",
  "Sunew Filmes Fotovoltaicos Impressos S.A",
  "Riz Boardshorts Ltd",
  "Global Emergency Group (GEG)",
  "Mutu Coffee Roasters, LLC",
  "MATCHA KAORI MEXICO SA DE CV",
  "SPYGEN",
  "Food Insight Group",
  "Freemet Comercial SpA",
  "CONNEXING",
  "VivoPower International PLC",
  "Apolitical Group Limited",
  "Experience Momentum Physical Therapy, Nutrition & Fitness",
  "Aguagente S.A.P.I. de C.V.",
  "Impact Hub Madrid",
  "Invincible Unicorn",
  "Combustibles Alternos Sustentables SA de CV",
  "Rayito de Luna S.A",
  "Rever Consulting",
  "WattValue SARL",
  "Heart in Business Limited",
  "Toast Ale",
  "Tippytea Blends",
  "Revalue",
  "BUNA",
  "Smartrip",
  "El Definido",
  "WakaWaka",
  "COMBIO ENERGIA",
  "GlobeScan Incorporated",
  "FRUANDES",
  "Abhati",
  "Reunion Island Coffee",
  "TAS",
  "NOVO Painting & Property Services LLC",
  "The Delphi Group",
  "KYA Inc",
  "Arabella Advisors",
  "Climate Smart Business, Inc.",
  "Intexo Società Benefit S.r.l.",
  "Waldron",
  "Bullhorn",
  "Inka Moss S.A.C.",
  "Coffee Flour Global Holdings",
  "DoseBiome Inc.",
  "Borealis GeoPower Inc.",
  "DIVERSA",
  "La Cristina",
  "ESCALA Educacion",
  "KAWSAY",
  "Wenu Work",
  "The Key - Prosperar na Nova Economia",
  "CLINICA OREMA",
  "Modern Energy",
  "Relewant SA",
  "Radfield Home Care Ltd",
  "BH Compliance",
  "Better World Fashion",
  "Northern Village Inc",
  "City First Bank",
  "Global Works",
  "Green Hammer",
  "Cooperative Coffees, Inc",
  "Apostrophe, Inc.",
  "Borders Perrin Norrander, Inc.",
  "Cascade Web Development, Inc.",
  "Carpe Diem Education",
  "C.F. Martin & Co., Inc.",
  "Keel Creative",
  "MoreDream Inc.",
  "Smart Set, Inc.",
  "Better World Club, Inc.",
  "The Renewal Workshop",
  "Stoller Family Estate",
  "The Scott Farm",
  "Grounds For Change",
  "Prepare Inc",
  "Landit",
  "Visit.org",
  "Pisticci Restaurant",
  "Kinetic Communities Consulting",
  "Echo&Co",
  "A&R Solar",
  "TEN OVER STUDIO",
  "Walden Local Meat",
  "Prosperity Organic Foods",
  "LES VERGERS DU MEKONG JSC",
  "CSRware, Inc.",
  "City Of Roses Disposal & Recycling Inc | COR",
  "FloBeds",
  "Workit Health, Inc.",
  "Rachio",
  "Quinoa Green Biotech Co. Ltd.",
  "DHM Research",
  "Teamsworld Innovation Inc.",
  "Mercaris",
  "Greenmedialab brand di SportMaker Srl",
  "Local To You",
  "ShoppingGives",
  "The Good Pencil Company",
  "NadaMoo!",
  "Evolvere S.p.A.",
  "Ecotone, Inc.",
  "Brains On Fire, Inc.",
  "Kudu Srl",
  "inKind",
  "Thrive Farmers International, Inc.",
  "Civilian, Inc.",
  "OverDrive, Inc.",
  "Headframe Spirits, Inc.",
  "Edizioni Green Planner",
  "Hiptipico",
  "Covintus, Inc.",
  "tek srl",
  "PALM SPA",
  "Habitech - Energy and Environment District",
  "Red Duck Foods",
  "Let Em Have It Salon",
  "Chengdu Longlive Pension industry development Co., Ltd",
  "Metalli Lindberg srl",
  "LAM Consulting SB",
  "International Napoli Network",
  "Valli del Bitto Trading spa",
  "Sorriso e Salute Srl",
  "Blair Lauren Brown Inc",
  "NWG spa",
  "Cafe Campesino and Sweetwater Organic Coffee",
  "Emmerre Srls",
  "Between the Sheets Inc.",
  "DIASEN SRL",
  "Xinca",
  "Incluyeme.com",
  "Zullo's Markets Inc.",
  "KINeSYS Inc.",
  "Inspire Commerce",
  "Maxwell Health",
  "CleanWell, LLC",
  "CleanFish",
  "Agora Partnerships",
  "Energy Opportunities",
  "Intelligarde International Inc.",
  "Spark cph ApS",
  "Fair-Green Creatives BV / WAAR",
  "Inflection",
  "Conservation Forestry Partners, LLC",
  "Best Organics, Inc.",
  "be",
  "Cyrus-Xp",
  "Abramar",
  "Socially Good Business",
  "C-Level Management, Inc.",
  "The Social Change Agency",
  "B Revolution",
  "Dewey's Bakery Inc.",
  "UHG",
  "Algramo",
  "Platinum Coaching Inc.",
  "Causecast",
  "Allegro 234",
  "Living School",
  "Tostadores de Ometepe",
  "Frontier Snacks",
  "Yoatz",
  "CREPiNi",
  "Emory Knoll Farms",
  "Community Sourced Capital",
  "Eudaimonia",
  "Net Balance",
  "Origin Climate",
  "VoIP Supply, LLC",
  "ReWork",
  "Farmigo",
  "Little Duck Organics",
  "Ogden Publications, Inc.",
  "ProtoTest",
  "Rally Software",
  "Hawaiian Ola",
  "FIGS",
  "Dapwood Furniture Co.",
  "Inward Point",
  "Centro-PACE",
  "BALANCE Edutainment",
  "Parties That Cook",
  "Social Stock Exchange",
  "Ecojot",
  "Carter Law Group",
  "Big City Farms Inc.",
  "Red Elephant",
  "Snakk Media",
  "TechChange",
  "99jobs.com",
  "Mobile Accord",
  "Tendril",
  "OneRoof, Inc.",
  "Asilia Africa Ltd.",
  "Kindred Studios",
  "Moonbird Designs Pty Ltd",
  "Global Cycling Adventures",
  "Little Tokyo Two",
  "Vita Global, Inc",
  "T Chapman Consulting & Associates",
  "FairWinds Advisors",
  "Power of Youth",
  "Thrive Consulting Group",
  "The Phoenix Advisory Group",
  "Tin Smart Social Ltd",
  "List Ventures LLC",
  "REAP NC, LLC.",
  "Right Hub srl",
  "1001PACT",
  "Synapse LLC",
  "Turbo",
  "BSD Consulting Colombia",
  "Orchard Advisors",
  "The Scott Petinga Group, GBC",
  "Connected Brands (Formerly Three Point Oh Ltd (t/a Three Point Zero))",
  "GoodBrand",
  "LiB Consultants",
  "Green April",
  "Clarity Recruitment",
  "Strateco Partners",
  "Tools4Change",
  "Fledge LLC",
  "ES Global Consulting",
  "Global Policy Solutions LLC",
  "Collaborative Coaching LLC",
  "WorkSmart Australia",
  "Brooke and Associates Consulting",
  "Seeds Consulting",
  "Place of the Future LLC",
  "Watershed Coaching, LLC",
  "Analytica Advisors Inc.",
  "La Bicicleta Gestión de Desarrollo",
  "Agova",
  "Kindred Spirit Consultancy Limited",
  "ESCO-Israeli Center for Social Business",
  "The Communications Refinery PBC",
  "iWE Studio",
  "TedSarvata.com",
  "Triple Ethos",
  "Learnical",
  "Springleaf Strategies",
  "MetaBrand Corp",
  "Compass(x) Strategy",
  "Manzimvula Ventures, Inc.",
  "The Work Playground",
  "Forsei Consulting",
  "Elephant Creative",
  "Compensation Venture Group, SPC",
  "Flagship CSR Consultancy",
  "Mandalah GmbH",
  "Adessy Associates",
  "The Projection Room",
  "Skiba Associates",
  "Climate Friendly Pty Limited",
  "AMÊNDOAS DO BRASIL",
  "Wire Media",
  "Eve-Volution Inc",
  "Hypenotic",
  "BioTerra",
  "Cultura Bank",
  "Oregon Cherry Growers, Inc.",
  "Leverage Lab",
  "MAX Insurance",
  "Yumbutter",
  "Channel Islands Outfitters",
  "Simple Energy",
  "EQi Group",
  "NewLevel Group LLC",
  "Leah B Noel CPA PC",
  "Technologies of Voice Interface Ltd.",
  "GOBILAB",
  "Tulip Winery LTD",
  "Threads 4 Thought",
  "Outcomes for Children (Core Assets Group) Limited",
  "Hugo Neu Recycling",
  "Cultivation Center",
  "Door To Door Organics",
  "Ideaction Corps",
  "HUMAN Healthy Vending",
  "Morning Indigo",
  "MadiDrop PBC",
  "Relay Foods",
  "Your Message Media",
  "GoLite - Original",
  "ZogSports",
  "Thermaflex North East Europe",
  "Pley",
  "TheGreenOffice.com",
  "Positive Impact S.r.l. SB",
  "Brix Media Co.",
  "R World Energy Solutions LLC",
  "NEUW Ventures SA",
  "Couchsurfing International",
  "Tembo Education",
  "Freelancers Insurance Agency",
  "More Than Money LLC",
  "Impact Hub Los Angeles",
  "Treeseed.Org",
  "Evox OmniMedia, PBC",
  "Local Food Lab",
  "Piedmont Biofuels",
  "The Bark House at Highland Craftsmen, Inc.",
  "Babytime! by Episencial",
  "Ecoservice",
  "Honeyman Sustainability Consulting, LLC",
  "M_s Ambiente S.A.",
  "CDI",
  "Capital Pacific Bank",
  "The Big Blue Bike",
  "Alchemy Goods",
  "SMART Watering Systems Inc.",
  "SLOWCOLOR",
  "Social Good Network",
  "Calor Energy",
  "Ideal Network, Inc.",
  "RosettaBooks",
  "NRG Insurance",
  "Relight Solutions",
  "GreenFox",
  "Croqqer",
  "Be Girl, Inc.",
  "Loka Swimwear Inc.",
  "New Avenue",
  "NurturMe",
  "Ovalie Intérim",
  "The Bear James Company",
  "Smart Receivables®",
  "FLOOW2 | World's Reset Button",
  "PayActiv, Inc.",
  "Laudex",
  "Fazenda Mãe d' Água",
  "Grupo Construcia",
  "Harvest Power",
  "MJ Everson Financial",
  "Quíron",
  "ZEBU Mídias Sustentáveis",
  "Bmov Ltda.",
  "GreenTomato",
  "eneache sa",
  "E3P",
  "Macías Gómez & Asociados Abogados",
  "Free Mind SAS",
  "BORDECHI",
  "Watson",
  "SIRPLAST",
  "Conexao Cultural",
  "ACTUA360",
  "Full Runners S.A.",
  "Enves",
  "VOZ Diseño y Exportaciones SPA",
  "Route to Green SPA",
  "Ecover Belgium N.V.",
  "Purpose Staff",
  "Waste To Green, LLC",
  "Woodfold Mfg., Inc.",
  "New Day Films, Inc.",
  "Advanced Home Energy",
  "Disconnect, Inc.",
  "Pots n Pans",
  "Ned Schaub Consulting -- Social Change Strategy",
  "Juhudi Kilimo",
  "SQA Pharmacy Services LLC",
  "Solmetric Corporation",
  "March 4th, Inc.",
  "SosDrinks",
  "Agents Of Change Partners",
  "Radix Consulting Group, LLC",
  "Atayne, LLC",
  "Numbers for Good",
  "Just Right Recycling",
  "ISTAG cic",
  "The New Media Group",
  "MAFIA",
  "Atelier 10",
  "Yellow108",
  "T4G Limited",
  "Bang The Table",
  "Kina'ole Capital Partners, LLC",
  "Yash Papers Limited",
  "Matter&Co",
  "Five AM Life Pty Ltd",
  "Grupo MIA",
  "Community Wealth Partners",
  "Fathom Delivers",
  "Fabled Frog Soap, Inc",
  "Green House Data",
  "Encourage Capital",
  "First Green Bank",
  "Smart Sustainability Consulting",
  "Neo",
  "Do It Green (DIG)",
  "Solid Ground Consulting",
  "Nourish Juice Bar",
  "Ten to One",
  "Almach Energy Ltd",
  "Public.",
  "Foster Care Technologies, LLC",
  "FusionSpark Media, Inc.",
  "Localize",
  "One Savvy Mother, LLC",
  "xrunner Venture GmbH",
  "Green Canopy",
  "Ouro Verde Amazonia",
  "Kinsu",
  "Cutting Edge Capital",
  "Communally",
  "Tomolla Consulting, LLC",
  "MSir Rest LLC",
  "Mountain Challenge",
  "Yapacopia Inc.",
  "Nature's Fare Markets",
  "Bluerise BV",
  "PACT Apparel",
  "Reynolds Jet",
  "The Reader",
  "Ruby's Naturals, Inc.",
  "Nova Sun Power",
  "Henley Club",
  "Human IT",
  "Peers",
  "Summit Creek Capital LLC",
  "Kitchenbug",
  "Blue State Coffee",
  ".Testpeople",
  "The Rose Group",
  "Bay Area Medical Academy",
  "Zero to Go",
  "Transplant Connect",
  "Eco Brands Group, LLC- Ecologic Designs/Green Guru/Alchemy Goods",
  "Aroundsquare Ltd",
  "GreenCitizen, Inc.",
  "Hugh Lofting Timber Framing & High Performance Building",
  "YogaLife Institute Inc.",
  "Coffee Enterprises",
  "The Root Collective",
  "Ecovantage",
  "People Who Global",
  "evain",
  "csr eco solutions",
  "Goodness Gracious Foods Ltd",
  "Better Life Mobile",
  "Impactivo Consulting",
  "SKT Education Group",
  "The Thx Co.",
  "Neema",
  "Junior Explorers Inc",
  "Flowing S.A.",
  "Riley Life Logistics",
  "B Corp Solutions",
  "Dikaios International",
  "JOB Associates",
  "Alkance Comunicaciones",
  "Open University Of West Africa",
  "CafeGive",
  "Insight Robotics Limited",
  "4 Good",
  "Teysha Social Enterprises",
  "Greenmont Capital Partners",
  "Kapa+ EcoSocial",
  "Institute B",
  "Future Energy Pty Ltd",
  "FlowOver",
  "New Earth Athens",
  "Source Intelligence",
  "Artemis Foods",
  "Takt-etik",
  "therethere",
  "Pacific Superfood Snacks",
  "Kitts",
  "RocketOwl Inc",
  "TSSS",
  "Ellen Weinreb Csr Recruiting",
  "Thinkhaus",
  "Koopman Ostbo Marketing Communicatiion",
  "AmeriCann, Inc.",
  "Clear Comfort Water",
  "CODETHIC",
  "Helping Hand Rewards",
  "BARE Snacks",
  "Concept Green",
  "Sensible Organics Inc.",
  "YR&G",
  "Incite Directives",
  "CAL Insurance & Assoc. Inc.",
  "Strategic Sustainability Consulting",
  "Expressyourshades",
  "Greenlight Planet",
  "Direct Dental Administrators, LLC",
  "In Ticketing",
  "PIMALPAKA SAC",
  "Sapience Financial & Investment Services",
  "ThinkImpact Company",
  "T2AP Creative Team",
  "sweetriot",
  "Goodfunds Wealth Management",
  "Impact Tech Pty Ltd",
  "Actuality Media",
  "Rhyme&Reason Clothing",
  "Tech Ranch",
  "Purposeful",
  "Green Grove Group",
  "SOURCE Local Foods",
  "CareAcademy",
  "Impact Hub Boulder",
  "SCS Global Services",
  "Icebox Knitting, LLC",
  "The Honest Company",
  "The Green Smoothie Bar",
  "Community Natural Foods",
  "DCG Strategies",
  "SANTOSH",
  "Shout",
  "Ecoenergias",
  "RainGrid, Inc.",
  "Tu clase, tu país",
  "iWOPI",
  "R&D GREEN SRL",
  "Ecosystems Group, Inc.",
  "GreenHouse Eco-Cleaning",
  "SOOKA INC / GLYDE America",
  "Social Designer Pty Ltd",
  "Ryan Nonprofits",
  "Viasyn, Inc.",
  "Bona Dea",
  "Newton Running",
  "Fmyi",
  "Corktown Seed Co.",
  "The Majora Carter Group LLC",
  "Impact Hub Geneva",
  "Zinc Pty Ltd",
  "Green Rising Marketing",
  "KUTOA Health Co.",
  "Já Entendi",
  "Fiddleheads Health & Nutrition",
  "Group 113",
  "Mobisol",
  "PPS",
  "Anthrome Insights",
  "PhilanTech",
  "Siw Thai Silk, Inc.",
  "DO GOOD Real Estate",
  "Skoodat, LLC",
  "Louder",
  "SER",
  "Green ABCs",
  "iNotForProfit",
  "Intendu",
  "All Across Africa",
  "Sungevity",
  "EnviroMedia, Inc.",
  "Causedirect",
  "Pwrdby LLC",
  "Avvya",
  "Green Alpha Advisors, LLC",
  "Peruvian Imports",
  "226strategic",
  "Advanced Innovation Center",
  "TaxiGo",
  "Cerco",
  "B-Green",
  "Media Citizens Ltd",
  "Brazil Impact Investing Management, LLC",
  "Unreasonable Media",
  "See3 Communications LLC",
  "Umega Lettings",
  "Nazori",
  "Thread",
  "Clean Ethics",
  "Education Funding Partners",
  "Ambiente Creativo",
  "China Credit Information Service",
  "Native American Natural Foods LLC",
  "The Female Social Network",
  "Oishi-m",
  "d.light design",
  "Conservation Impact and Nonprofit Impact",
  "Farm Dog Naturals",
  "More than Honey Lda - Beesweet",
  "GreenGoWeb",
  "Lucenza",
  "Sweet Temptations Cupcakery",
  "Pipsnacks LLC",
  "Comparte",
  "WaterSmart Software",
  "TriLibrium",
  "Big Room Inc.",
  "GreenForestry.us",
  "Talgra",
  "Persistent Energy Partners",
  "Cora",
  "gBuild Construction Managers",
  "Topical BioMedics, Inc",
  "Danuon Corp.",
  "JustNeem, LLC",
  "Musuchouse",
  "Sílice",
  "Etsy",
  "BAST B.V.",
  "Bed Bandits",
  "Ecoflora Cares",
  "Boa Energia, lda",
  "Lumen Energy",
  "SoupCycle",
  "Rimon, P.C.",
  "Social Asset Measurements",
  "1st Playable Productions",
  "InterSchola",
  "QStone",
  "FonoEmpleo",
  "Moving Forward Education",
  "Greca",
  "CAP Global",
  "Green Building Services",
  "The Hub Conshohocken, LLC",
  "Simply Gum",
  "LATITUD 90",
  "Software Anywhere, LLC",
  "Fission Strategy, LLC",
  "Totebag SRL",
  "AJ Financial Planning",
  "Closed Loop Advisors",
  "Green Home",
  "The Paradigm Project",
  "McEvoy Ranch",
  "Good Eggs",
  "RiskSOURCE Clark-Theders",
  "MAXX Potential",
  "Montgomery & Hansen",
  "KIVOY S.A.",
  "River City Comprehensive Counseling Services",
  "Impresión Uno",
  "Babyganics",
  "iSupportU",
  "Help2Heal",
  "Upcyclity Inc.",
  "Starwin Social Enterprise",
  "First Rate, Inc.",
  "ColorADD",
  "Revista Innovación Social",
  "OneEnergy Renewables",
  "Cuppow",
  "CarShare Atlantic",
  "Good Done Great, Inc.",
  "Bristlecone Advisors",
  "thrdPlace",
  "Ainsley's Pharmacy",
  "Policlínica Granato",
  "Wholly Hemp",
  "Falcon & Singer P.C.",
  "Ecopacto",
  "Thinkbaby & Thinksport",
  "Missbeez ltd",
  "IKUNA",
  "Contemporary-Craft",
  "Peerby",
  "Encore Wealth Advisors",
  "gb&d Magazine",
  "Cents",
  "Cubiertosdemadera.com",
  "RTOWN",
  "FGS&Co.",
  "Olomomo Nut Company, LLC.",
  "East Amber",
  "Vivid Accountants & Advisers",
  "i2 Capital Group, Inc.",
  "Buy The Change",
  "Sputnik Moment",
  "BacTech Environmental Corporation",
  "Actimpact SL",
  "EcoWatch",
  "Emprendejoven",
  "Opulent Group",
  "Good Tech America, LLC",
  "The Eco Laundry Company",
  "Swarm Ventures",
  "TriplePundit, LLC",
  "Practice Makes Perfect Holdings PBC",
  "Softcare",
  "Ripple Strategies LLC",
  "Folk Digital Ltd",
  "Esse Limitada",
  "Ecocreative",
  "Benefit Capital",
  "DePaul Packaging",
  "Assemblyfor",
  "Impact Insurance Agency",
  "ADDvocacy ADHD & Life Skills Coaching ltd",
  "Invested Development",
  "National Foundry Products",
  "Vyykn Inc",
  "El Dot Designs",
  "Staffordshire Chambers of Commerce",
  "Tigh na Mara Salen Limited",
  "Wisdom of Crowds Ltd",
  "Counter Culture",
  "I Am Possible Ltd",
  "Six Degree People",
  "Affect Conf, LLC",
  "Starvation Alley Farms",
  "Pasture One",
  "BABYONICA",
  "Kooks & Co",
  "Crowdpac",
  "PAEZ just",
  "CoPower",
  "ZORA",
  "Warby Parker",
  "Brenthaven",
  "Conscious Public Relations Inc.",
  "Casper",
  "Mondo Mediaworks, Inc.",
  "The Australian Educational Travel Company",
  "Squag Inc.",
  "Bison Media",
  "Fearless Unlimited LLC",
  "Ethical Bean Coffee",
  "Mugshots Coffeehouse",
  "Fotoraporto S.L.",
  "Social Atlas",
  "Red Rabbit",
  "WorkSquare",
  "Heidi.com",
  "Peer",
  "Lucid.Berlin",
  "Banca Prossima",
  "SUBISO GMBH",
  "Fomenta Gestão",
  "Práxis Socioambiental",
  "SOS DENTAL",
  "The Products Comercial Ltda.",
  "Feiticos Aromaticos",
  "Preting",
  "HH Logistics Planning, LLC",
  "Fig Food Company, LLC",
  "Hamilton Perkins Collection",
  "Dadavan Systems",
  "Kabrita USA",
  "Love Child Organics",
  "Picaroons",
  "Scout & Burrow Consulting",
  "Xerion Dispensary",
  "BBoards.org",
  "Old Town Glassworks",
  "Komodo OpenLab Inc.",
  "Prairie Paper",
  "The Detailing Knights",
  "Thriver Inc.",
  "Homestead Organics",
  "Maritime Tidal Energy Corporation",
  "ChangeIt",
  "Fresh City Farms, Inc.",
  "Newstart Canada",
  "Sustainability Television",
  "Living Forest Communities",
  "DeConi",
  "Union Kitchen",
  "Jardín Pintacuentos",
  "Artifex Financial Group",
  "THREE SISTA'S",
  "AguaClara LLC",
  "Jibu",
  "WorthWild LLC",
  "Arcadia Power",
  "Mindfull Investors",
  "Investment Management Consultants, Inc",
  "With Good Reasons, LLC",
  "CardioReady",
  "Wynn Capital Management",
  "DoubleDividend Management B.V.",
  "Artisan Connect",
  "Graines de Changement",
  "Clean Markets",
  "Make a Stand Inc.",
  "2b Design",
  "PLUSfoam",
  "Casa e Cafe",
  "ETAVENCA",
  "Instituto Muda",
  "Linhardt Design",
  "Imprint Capital",
  "VeeV Spirits",
  "CIS",
  "Interface Sustainable Constructions",
  "RedShip LLC",
  "Gazelle Sports",
  "Chamana",
  "Jackson River",
  "Onda Organica",
  "Twirl Management",
  "Bioplanet Corp.",
  "Wildwon Projects",
  "Pivot Energy",
  "Gentexpresa",
  "Kimpacto, Inc.",
  "Enova",
  "1051 by GOODONYA®",
  "Inkkas",
  "TTC",
  "Trum Handcycles",
  "Equilibrium Srl",
  "Yummari",
  "Hive Projects",
  "Nutiva",
  "Modulab Ecodiseño ltda",
  "Dan Vaughn Law",
  "Susty Party",
  "Brand Cool",
  "Hobson Bernardino + Davis LLP",
  "Thermaflex North West Europe",
  "MAONO",
  "The Church Palace",
  "Grupo Unite",
  "Willem&Drees (old)",
  "Made Blue",
  "Ivy",
  "Greenlink Energy BV",
  "Reformation",
  "Adjacent Consulting",
  "SSC WOOD",
  "2 Point Perspective",
  "Little Bean Sprout",
  "Organic Media Network",
  "Cíclica SRL",
  "Shark Island Productions Pty Ltd",
  "USEED",
  "DwellTek",
  "Main Street Benefits",
  "Lindes",
  "Equitable Origin",
  "Byoearth",
  "Lovesocial",
  "Bigger Boat Consulting",
  "Sechler CPA PC",
  "Womenetics",
  "Sustainable Solutions Corporation",
  "Grower's Secret, Inc.",
  "Bum Boosa Bamboo Products",
  "Love & Hummus Co., LLC",
  "Madhava Sweeteners",
  "Renewable Choice Energy",
  "Swift River Consulting",
  "Cutting Edge Counsel",
  "Freeflow Digital",
  "Dapple",
  "Emerge Financial Wellness",
  "Mosaic",
  "Elefint Designs",
  "IGNIA Partners LLC",
  "Free Range",
  "Murex Investments",
  "Bison Brewing Company",
  "Savenia LLC",
  "Toniic",
  "New Resource Bank",
  "Dansko",
  "The Arnold Development Group",
  "Servals Automation Pvt Ltd",
  "Shree Kamdhenu Electronics Pvt. Ltd.",
  "Charleston Travel Limited",
  "Liberty Tonerserv",
  "Luftman, Heck & Associates, LLP",
  "I AM Enlightened Creations",
  "Cleantech Law Partners",
  "Mission Markets",
  "allGreenup",
  "Discovered",
  "Care2",
  "BeOneOff",
  "The Natural Baby Company",
  "Modo Design Group Inc.",
  "Proyecto Importa",
  "Rosen",
  "Restore Capital",
  "NextSpace Coworking & Innovation, Inc.",
  "Envirofit International Inc",
  "Lightspan Digital",
  "One Earth Designs",
  "Duggan's Funeral Service",
  "FutureProof, LLC",
  "WattElse",
  "SNP Strategies, Inc.",
  "No One Without",
  "OMBE",
  "Pure Sweets, LLC",
  "POMADA",
  "Bend Law Group",
  "La Costurera",
  "In Posse",
  "Delight Co., Ltd.",
  "Cr Surf Travel Company",
  "BOULD",
  "Fulcrum Creatives",
  "Britec Ltda.",
  "Next Generation Consulting",
  "Sustainable Earth Solutions, Inc.",
  "Blue Earth Consultants, LLC",
  "ForceBrain.com",
  "Gilded Rogue Enterprises, LLC",
  "Habitación y Vida Hábvita",
  "IdeeGreen S.r.l.",
  "Global Centre of Research and Engagement",
  "Taste Creative",
  "Chopwood, LLC",
  "Community Buying Group",
  "Evident (evident.co.nz)",
  "Azul Seven",
  "SavinGreen",
  "Conservation Investment Management, LLC",
  "Thrive Impact Sourcing, LLC",
  "Law Plus Plus",
  "Clinique VI",
  "The Tartan Group",
  "Officina della Terra",
  "We.Build (webuild.io)",
  "soulpepper",
  "Cherryfish",
  "Adama Capital",
  "Koiki",
  "MakerKids",
  "CUA",
  "Greener Inspections",
  "BEYOND",
  "Thermaflex Central Europe",
  "Jordan Inc.",
  "Bonsum",
  "100 Percent Wine",
  "Marioway Srl SB",
  "NAIA PROJECT",
  "AFC Health Limited",
  "WebChair",
  "MyDomino",
  "Logframe - Consultoria e Formação, Lda",
  "Sweet'tauk",
  "Intrinsi",
  "GO Box",
  "Honeyman Design Studio",
  "616 Lofts",
  "N/A",
  "B Storytelling",
  "Vermont Smoke & Cure",
  "Postcard.com, PBC",
  "SAGA Arquitectos",
  "Build With Prospect Inc.",
  "EcoSTEPS",
  "RNL Design",
  "ADAPT by Design",
  "WIAN Branding",
  "Carleton Law Group",
  "Snoqualmie Ice Cream",
  "Ecolohas Energy Technology Co,. Ltd",
  "FarmRaiser LLC",
  "WeeWork for Good",
  "Zekogram Innova S.L.",
  "The Color Mill",
  "Privalore Inmuebles SL",
  "caos! comunicação & design",
  "DeDora Capital",
  "Sanosnack",
  "The 3D Printer Experience Benefit Corp.",
  "IZZY",
  "The EarthKeeper Alliance",
  "Green Ideas, Inc.",
  "Vora Certified Public Accountants",
  "plenum - society for holistic sustainable development GmbH",
  "GoGreen Telas",
  "Cometech Srl",
  "Essence Restaurant Group",
  "Software for Good, GBC",
  "Project Repat",
  "Payton Communications LLC",
  "The Big Idea Bookstore",
  "i-Immersion Institute",
  "OtoSim Inc.",
  "Percolate Galactic",
  "Merchants of Green Coffee",
  "Vedante Corp",
  "Durham Co-op Market",
  "Homesol Building Solutions Inc.",
  "YouCaring Dot Com, LLC",
  "eWaste Tech Systems, LLC",
  "Best Home Healthcare Network Inc",
  "GoGreen Store Srl",
  "Boond Engineering & Development (P) Ltd",
  "LQF",
  "League of Extraordinary Women",
  "Thread Publishing",
  "Negosyong Pinoy Venture South Finance Corporation",
  "Macroclimate®",
  "Katie M Snyder & Associates",
  "ImpactFlow, Inc.",
  "Calstone Inc.",
  "Temple Flower",
  "TerraLocke, Inc.",
  "Deep Ecology",
  "InVenture",
  "egg",
  "Pachamama Coffee Cooperative",
  "Hives for Lives",
  "Mindful Investors",
  "Ecobalanza",
  "Good Capital, LLC",
  "Berger & Fohr",
  "Lawlignment",
  "Feelgoodz LLC",
  "GreenLine Paper Company, Inc.",
  "Big Vision Media Group",
  "Lateral Line, Inc.",
  "TBL Capital",
  "Intrepid Group Ltd",
  "Davines",
  "Crepes y Waffles Colombia",
  "Bjorg Bonneterre et Compagnie",
  "Hortifrut Chile",
  "O-Bank",
  "The Bama Companies Inc.",
  "Hovione FarmaCiencia SA",
  "Danone North America",
  "Chiesi Group",
  "The Myers-Briggs Company",
  "Laureate Education",
  "Arowana International",
  "Biofilter Environmental Co.",
  "Home Leasing",
  "Conservatorio SA",
  "Benefit Systems"
];
